### ISSUE TITLE
(Probably) LuaJIT problem for raspberry pi 4b, partially solved

### ISSUE THREAD

**Issue by Adriankhl** [minetest/minetest#10895]
##### Minetest version
5.3

##### OS / Hardware
Operating system: raspberry pi os 64bit (Debian arm64)
Model: Raspberry pi 4B 8GB

##### Summary
Minetest crashes (segfault) occasionally when trying to show server lists in "Join Game" tab

##### Steps to reproduce
Open minetest
If not already at the "Join Game" tab, click that
Sometime it crashes after printing `Loaded texture: /home/pi/git/develop/minetest-project/minetest/textures/base/pack/server_flags_pvp.png`

##### Problem analysis and solution
So I have compiled it in debug mode and run it with gdb, unfortunately the backtrace at the crash moment is full of question marks. Just before the crash there are a few threads running and some of them are downloading the server lists with some luajit call.

From my experience, luajit from debian repo can be problematic on raspberry pi. Therefore, I clone the luajit source code from `https://github.com/LuaJIT/LuaJIT.git`, modify the stack size at `src/luaconf.h` then build and install it. Building Minetest with this version of luajit seems to solve the problem.

Is there anything that can be done within minetest to solve it without having to build a custom luajit?

##### Minor new problem
I need to lower the resolution to run minetest (fullscreen) smoothly on raspberry pi. It seems like the resolution cannot be restored after closing minetest if I build minetest with the custom luajit. I need to use the following bash script to automate it
```
#!/bin/bash

xrandr --output HDMI-1 --mode 1280x720
cd ${HOME}/git/develop/minetest-project/minetest
./bin/minetest

wait
echo "Done: restore resolution"
xrandr --output HDMI-1  --preferred
```

**Comment by sfan5** [comment]
> From my experience, luajit from debian repo can be problematic on raspberry pi. Therefore, [...]. Building Minetest with this version of luajit seems to solve the problem.

That's my first time hearing of this. Generally, LuaJIT works well on ARM64 and I've confirmed this myself.
If Debian/Raspbian ships a broken version of LuaJIT that's their problem.

You can also try the current development state (5.4.0-dev) and see if this has somehow been solved in the meantime.

> It seems like the resolution cannot be restored after closing minetest if I build minetest with the custom luajit.

The builtin fullscreen mode is bad, known issue, see #4921.

**Comment by Adriankhl** [comment]
> You can also try the current development state (5.4.0-dev) and see if this has somehow been solved in the meantime.

Tried, it still crashed. Building luajit from source (even without modifying the config) solve the problem. Now I am pretty confident that it is Debian's problem. Maybe the newer version in the Debian Testing repo can fix the problem, but I am not going to mess up my system to test that. I will close this issue and keep this as a reference for anyone who uses Debian arm64.

> > It seems like the resolution cannot be restored after closing minetest if I build minetest with the custom luajit.
> 
> The builtin fullscreen mode is bad, known issue, see #4921.

Alright, I managed to use `xdotool` to automate the windows mode into fullscreen
```
#!/bin/bash

xrandr --output HDMI-1 --mode 1280x720
cd ${HOME}/git/develop/minetest-project/minetest
./bin/minetest &

sleep 2
xdotool key alt+F11

wait
echo "Done: restore resolution"
xrandr --output HDMI-1  --preferred
```
