### ISSUE TITLE
Remove `repeat_place_time` setting, it's plain cheating

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#12493]
Split from #12140

## Problem
People abuse of this setting to build way faster. This happens in my server when people play skywars and also on other servers like CTF. Quoting an user from our Matrix:
> yeah, on the main CTF server you can find almost everyone abusing that feature

## Solutions
Remove it entirely. I can't think of any usecase where this setting might actually be helpful, but I can think of a lot of usecases where this is harmful

EDIT: @appgurueu has suggested that it might be useful for creative. But that's why things like World Edit exists, also because you'll lack control when the value is too low (building columns aside whilst looking down)

## Alternatives
---

**Comment by appgurueu** [comment]
# Alternatives

## [Server-sent settings](https://github.com/minetest/minetest/issues/11227)

This would allow servers to simply override / disable / clamp such settings entirely, similar to CSM restrictions.

## Server-side rate limiting

Probably required either way, if only to detect cheaters that auto-spambuild structures. I've implemented this in the form of:

* [`place_limit`](https://github.com/appgurueu/place_limit), a somewhat outdated mod;
* [a CTF PR](https://github.com/MT-CTF/capturetheflag/pull/803 and [a follow-up one](https://github.com/MT-CTF/capturetheflag/pull/844), which both got merged (and later reverted/disabled since the setting abusers whined about them and/or they were poorly configured)

Modders have various options here: quotas, hard required wait time between two node placements, "energy" etc. Obviously this doesn't work well with clientside prediction (nodes disappear on the client). Disabling clientside prediction altogether is no option. There must be a proper way to communicate the limits to the client.

Logically, if digging is time-limited, why shouldn't placing be?

**Comment by Zughy** [comment]
I agree that server-sent settings can be useful, but I also think that in this case, the setting makes no sense to exist in the first place

**Comment by rubenwardy** [comment]
I can see this being the sort of thing that's useful for accessibility, but only when the value is increased. There should at least be a minimum bound and it should also be limited on the server-side

**Comment by Desour** [comment]
Having a server-enforced limit probably makes sense, for games where such a restriction is wanted (this is not all games, i.e. not those where building faster doesn't make it easier to gain resources).

Maybe implement it as a player pyhsics override field?

The client-side setting is still useful, so that players can still decide to place slower than the maximum allowed. (This is probably the accessibility ruben was referring to.)

Please keep the default at infinity, for backwards compatibility, and because any other default would be either arbitrary, and hence unjustified, or the current default of the client-side setting, which is a too slow for my personal taste.

**Comment by Zughy** [comment]
> so that players can still decide to place slower than the maximum allowed. (This is probably the accessibility ruben was referring to.)

I still don't get the accessibility reference. Can someone give me a practical example?

**Comment by Desour** [comment]
> I still don't get the accessibility reference. Can someone give me a practical example?

If I set `repeat_place_time` low enough and use my touchpad to place, it places multiple nodes at once.

**Comment by sfan5** [comment]
Meeting decision: We will add code to clamped this (to the current value?) for 5.6.0.
A way for the server to control this kind of delays (e.g. also `object_hit_delay`) should be worked on for future versions.

**Comment by Zughy** [comment]
See PR above, closing
