### ISSUE TITLE
FPS limiter is inaccurate compared to other games (fixed on Linux)

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#13399]
##### Minetest version

```
5.7.0
```
##### OS / Hardware

Operating system: Linux
CPU: Intel Core i9-13900K

GPU model: GeForce RTX 4090 (NVIDIA 530.41.03)
OpenGL version: OpenGL 4.6

##### Summary

Minetest's FPS limiter renders more frames than requested. This is a problem when attempting to reach a stable framerate below the V-Sync threshold for [low input lag with V-Sync enabled when using a variable refresh rate monitor](https://blurbusters.com/howto-low-lag-vsync-on/).

I've had decent success using `fps_max = 110` to target 117 FPS on a 120 Hz display, but even then, it will occasionally go above 117 FPS (which causes temporarily increased input lag).

The screenshots below show both Minetest's own FPS counter and a MangoHUD overlay to prove that Minetest's FPS counter isn't the issue:

**`fps_max = 100`**

Expected time between frames: 10.0 ms

![Screenshot_20230408_231239](https://user-images.githubusercontent.com/180032/230742888-d7ebe19e-3212-4b0f-a041-4816f1dced7d.png)

**`fps_max = 150`**

Expected time between frames: ~6.7 ms

![Screenshot_20230408_231336](https://user-images.githubusercontent.com/180032/230742902-02f44d48-a5ad-48ea-8a6b-4234cecd767a.png)

**`fps_max = 30`**

Expected time between frames: ~33.3 ms

![Screenshot_20230408_231435](https://user-images.githubusercontent.com/180032/230742903-9bd5b0a5-68e5-4d0e-b59c-53a62ef540c4.png)

##### Steps to reproduce

Set `fps_max` to any value and notice how the FPS cap is exceeded by the game. This can be verified both using Minetest's own FPS counter, but also external tools such as RTSS and MangoHUD.

**Comment by Desour** [comment]
We're only sleeping with ms resolution (very coarse):
https://github.com/minetest/minetest/blob/9d736e8b8baeeacad9cfa94edd18adfcaf000029/src/client/game.cpp#L4252

**Comment by sfan5** [comment]
That is a leftover from when the entire code operated with ms, feel free to test with higher accuracy.

**Comment by srifqi** [comment]
Is this issue Linux-spesific? I can not reproduce it on mine (Windows 10/10.0.19045, AMD Ryzen 5 4500U with Radeon Graphics). The FPS never goes above the limit.

![FPS on Minetest vs on Xbox Game Bar](https://github.com/minetest/minetest/assets/4017302/cebd19db-a510-4e00-a602-eee2c0c1d00e)

(setting `fps_max = 30` and using Xbox Game Bar on Windows, <kbd>Win</kbd>+<kbd>G</kbd>)

**Comment by Zughy** [comment]
`fps_max = 30`. Is this wrong? Also, why FPS on MT always says 29?

https://github.com/minetest/minetest/assets/63455151/016a9bb4-e7d1-4315-a0b3-1379aaac71ab

**Comment by sfan5** [comment]
Might be solved on Linux due to #13445

**Comment by Calinou** [comment]
> Also, why FPS on MT always says 29?

It's likely a rounding error (perhaps it's floored in one way or another instead of using `round()`).

**Comment by Zughy** [comment]
So, to be clear, this is fixed? I didn't get it, sorry

**Comment by Calinou** [comment]
Seems to work great as of a98200bb4:

![Screenshot_20231211_123208](https://github.com/minetest/minetest/assets/180032/28f80d81-9f29-42c2-aebd-51b05d7e4e1b)

**Comment by sfan5** [comment]
It's fundamentally the same issue, just a different platform.

**Comment by srifqi** [comment]
After further testing, it does seem like the FPS limiter is still broken on Windows (Windows 10/10.0.19045, AMD Ryzen 5 4500U with Radeon Graphics).

I tested it with `fps_max = 114` using Xbox Game Bar on Windows (<kbd>Win</kbd>+<kbd>G</kbd>).

| `5.0.1` | `5.7.0` | `5.8.0` |
|:-------:|:-------:|:-------:|
|  50 FPS | 118 FPS | 116 FPS |
| ![5.0.1](https://github.com/minetest/minetest/assets/4017302/1b4c3f13-2098-4719-bb74-6a8f822bee06) | ![5.7.0](https://github.com/minetest/minetest/assets/4017302/69c6d02a-ec11-45a4-bdd9-2884a77c4328) | ![5.8.0](https://github.com/minetest/minetest/assets/4017302/4fe94d57-f173-4900-a435-dcc1bf957d33) |

**Comment by srifqi** [comment]
I found another issue with FPS limiter. When I run Minetest by compiling at `5.8.0` tag using MSVC (Release configuration), my FPS is capped at around 35 FPS. This does not happen when I run Minetest from the official `5.8.0` release for Windows (compiled with MinGW, I assume): I can get much higher FPS using that. Is there any difference in calculating FPS limit between compilers?

**Comment by sfan5** [comment]
Please test my PR. It might just happen to get fix that too.

**Comment by srifqi** [comment]
> Please test my PR. It might just happen to get fix that too.

The PR does not fix my issue.

**Comment by srifqi** [comment]
After further checking, I found that the FPS is limited to around 35 FPS when the debug info is shown (<kbd>F5</kbd>). Again, this only happens in MSVC, not in MinGW.

| Without debug info | With debug info |
|:------------------:|:---------------:|
| ![5.8.0 MSVC without debug info](https://github.com/minetest/minetest/assets/4017302/9624511e-1782-4522-ba2d-201d9c87dd06) | ![5.8.0 MSVC with debug info](https://github.com/minetest/minetest/assets/4017302/69cb370e-f6a1-4f9b-a895-86a2cf94bb2c) |

**Comment by sfan5** [comment]
Sounds like some weird (msvc-specific) inefficiency with text rendering.

**Comment by srifqi** [comment]
It has a lower FPS with lots of text in chat.

![Slow MT with lots of text](https://github.com/minetest/minetest/assets/4017302/6673b4c8-5deb-4c5b-b0d9-7b2bad5a547b)

Opening the chat console window lowers the FPS significantly.

![Slow MT with lots of text](https://github.com/minetest/minetest/assets/4017302/0e5ecd85-b2a2-4c5c-b929-9b12b5f1a0ff)
