### ISSUE TITLE
disable_jump group doesn't work on nodeboxes

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#1551]
**doc/lua_api.txt:**
`- disable_jump: Player (and possibly other things) cannot jump from node`

*Test with [this mod](https://forum.minetest.net/viewtopic.php?f=11&t=9891).*

Unlike expected, the player can still jump. This is believed to be broken by MirceaKistune's physics changes back in late 2012-early 2013.

**2015-01-28:** the bug is still here. **It only happens on nodeboxes, full solid nodes work as expected.**

**Comment by gregorycu** [comment]
@Calinou I just tried testing this, and set disable_jump=1 and indeed I couldn't jump on the node. Are you able to confirm this is fixed?

**Comment by Calinou** [comment]
> @Calinou I just tried testing this, and set disable_jump=1 and indeed I couldn't jump on the node. Are you able to confirm this is fixed?

I have tested this again, and the conclusion is that `disable_jump = 1` works on full solid nodes, but not nodeboxes (except if you're sneaking on a nodebox and thus glitching – in this case, you can't jump).

**Comment by PilzAdam** [comment]
I can confirm that this is only broken for nodebox nodes (i.e. it works for "full" nodes).
Another thing I noticed while testing this is that jumping while standing still on a trampoline shoots you up into the sky. Is that the expected behavior?

**Comment by Calinou** [comment]
> Another thing I noticed while testing this is that jumping while standing still on a trampoline shoots you up into the sky. Is that the expected behavior?

No, it certainly isn't (it used to work fine before).

https://github.com/minetest/minetest/issues/1552

**Comment by gregorycu** [comment]
Thank you both for your comments, I'll try this out with nodeboxes and work on a fix tonight (for the jumping issue, not #1552)

**Comment by gregorycu** [comment]
I tried applying disable_jump=1 to stairs, and it seems to work as expected. Is there a particular none that doesn't work?

**Comment by Calinou** [comment]
> *Test with [this mod](https://forum.minetest.net/viewtopic.php?f=11&t=9891).*

**Comment by gregorycu** [comment]
This actually has nothing to do with jumping, or nodeboxes (at least directly). The engine is miscalculating what node the player is standing on.

I'll work on a fix.

**Comment by gregorycu** [comment]
This is fixed by https://github.com/gregorycu/minetest/commit/3ff4458bda5643591093a442ac74b044399bf356

Calinou, are you able to confirm?

**Comment by Calinou** [comment]
> Calinou, are you able to confirm?

I have tested this and it works, thanks.

**Comment by kwolekr** [comment]
Can confirm, works for me too.  Closing this.

**Comment by est31** [comment]
The according PR doesn't seem to be closed, and an user has reported it still doesn't work. Assuming mistake.

**Comment by veikk0** [comment]
Can also confirm it doesn't work, tested with the jumping mod linked in the description. However, placing one cushion on top of another disables jumping on the topmost one so it'd seem that the engine does miscalculate the node the player's standing on.

A related observation: jumping on a stacked pile of cushions from ground level while holding down the jump button allows the player to jump from a cushion. Holding down the jump button while walking off two stacked cushions also allows the player to jump. Both of these could be caused by the same bug.

Tested on 0.4.12-7bbb9b0

**Comment by kwolekr** [comment]
https://github.com/minetest/minetest/commit/5c3c965c1a6e1fb5957d441c2d04d8470b80d710
