### ISSUE TITLE
Mouse & keyboard on Android

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#2113]
Hi. More people connect keyboard & mouse to Android tablet (otg use).
Minetest don't support keyboard on Android.

**Comment by sapier** [comment]
Low level input handling is done by irrlicht. As Irrlicht does support keyboard I'm surprised it's supposed to not work. Did you try it?

**Comment by MoNTE48** [comment]
Bad mouse work and don't work change keys.
I test this now. Wait

**Comment by MoNTE48** [comment]
I tested.
Keyboard:
Starting game, connected keyboard. Crash!
Connected keyboard - start game - all work. Before, i can't change keys!
Mouse:
Hmm. No crash. Camera don't work, i can press GUI button, can PRESS left key and rotate camera.
Bad...

**Comment by KodexKy** [comment]
Fixed this, i'll make a PR in a few minutes after some testing.

**Comment by MoNTE48** [comment]
@KodexKy ok! Wait your commit!

**Comment by est31** [comment]
I can't reproduce anymore. Can this be closed?

**Comment by paramat** [comment]
#2120 is merged and seems fixed.

**Comment by farooqkz** [comment]
Hello. I just tested today and the problem is not completely fixed. There seem to be keyboard support(tested with bluetooth keyboard) and mouse support for the menu(connected a mouse through OTG). But in game there is no enough support. I have to simulate touch sweep with mouse to make it work. Let me know and I can test further or record the screen.
