### ISSUE TITLE
Add or update textures dynamically at runtime

### ISSUE THREAD

**Issue by Warr1024** [minetest/minetest#3528]
Allow server-side mod code to modify textures at runtime, i.e. replace an already-loaded texture with new image file content.  If feasible, also allow loading new textures, i.e. not present at server start time (which would be usable by entities).

Some use cases:
- A player skins mod, allowing players to customize their skins individually.
- Signs mods, allowing custom text (without creating a ton of individual entities) and/or custom graphics and styling on signs.
- Changing global appearance of nodes without changing nodedefs, such as for a "seasons" mod that might change global leaves/grass colors over time.

Ideally, the API would allow loading images from places other than the mod's original media subdirs, such as from a mod-provided temp file path, a binary string, or maybe even a URI (curl support?).

Support for asset types other than just textures (e.g. audio, models) would be nice too.

**Comment by sofar** [comment]
This is already possible, and it's a giant cause for problems - a reason why signs_lib has been disabled on so many servers. It causes a lot of lag to send generated textures to clients, especially in areas with lots of signs. Note that it can take sometimes a minute before you can even see the sign text texture on some servers.

I'm not dismissing the need for "changeable appearance" part of this feature request, but specifically to the implementation suggestion that you make.

As for signs, I'm convinced that signs should be rendered *client-side*. All the bits needed are already in the code. The client knows what a sign is and could easily use the cguifont/irrlicht support to render font text on the node surface. Other sign like nodes could easily be supported, and this would remove the need to send *any* new node data over the network, *and* does not need a protocol change (just an updated client version that supports this).

As for seasons - this seems like it is something that could be added client-side in the form of shaders or similar, again without requiring any new protocol or API change, other than a way to convene the changing of seasons to a client.

**Comment by sofar** [comment]
agreed there should be "resource packs" and not "texture packs".

**Comment by Warr1024** [comment]
It looks like signs_lib actually does the exact opposite, i.e. it sends commands to the client to build the sign texture, rather than push an updated already-built texture to the client.  For instance, see https://github.com/VanessaE/signs_lib/blob/master/init.lua#L382.

As for having Irrlicht render sign text client-side, it already does, if you're not using signs_lib; it displays in the "info text" area on the HUD, and signs_lib probably came about because people wanted more control over *how* the text was rendered.  I think that's really the core issue here: when you look at the way that signs_lib abuses the ^[combine operators, and the existence of issues like #3510, it's evident that mod authors are trying to find ways to have more control of textures *after* the server has loaded, at run-time.

As long as it works, I'm not too picky about the implementation.  I figured that it would probably involve the least amount of work, and add the least complexity, to just re-use the existing media transfer mechanism used when players emerge, but if anyone has an idea for a better implementation approach, we can discuss it here.

**Comment by sofar** [comment]
> As for having Irrlicht render sign text client-side, it already does, if you're not using signs_lib; it displays in the "info text" area on the HUD

that's not what I mean - I mean for the sign text to be rendered on the surface of a node itself, not in a HUD element.

**Comment by slemonide** [comment]
I think it would be beneficial to have an API for creating procedural textures at the runtime. That way it would be possible to draw dynamic world maps, make dynamic player skins (facial expressions?) and add more decoration tools.

**Comment by Jordach** [comment]
I would much prefer a way to combine textures as a *table* not a
texture1^texture2 style system. Using a string is long, and egregious -
ain't nobody got time for that.

A table however, might look like:

minetest.register_texture_modifier( "sometexture_name", {
"noise_texture_name", "texture2.png" } ) -- overlays texture2 over noise.
gives result's texture name as sometexture_name

I could mention that "sometexture_name" could be returned as a string - so
it could be used within a node definition, or a variable.

Which, obviously could be extended into drawing noise textures.

minetest.register_noise_texture( "noise_texture_name", "perlin / simplex /
etc", 16, true ) -- name of texture, noise type, size in px^2 and alpha
transparency. (For blending noise onto smooth textures.)

Having a proper image transformation system is far better than the terrible
mess we have currently.

**Comment by everamzah** [comment]
What was said about rendering text on a node sounds pretty exciting, and obvious for signs.  A compliment to tiles = {}, could be textoverlays = {}, being 6 strings for the node text.

**Comment by slemonide** [comment]
Maybe something like tile_overlays = {{"first overlay"}, {"second overlay"}, ...} would be better? That way if we would want to modify texture we wouldn't need to send the whole texture each time. Besides that, this will extend this feature for all tiles, not just text. As for the text, it can be drawn like this: text_tile = minetest.render_text("text"), where text_tile will be the name of the overlay texture with text.

**Comment by sofar** [comment]
@slemonide  that is not the right way to design an API.

**Comment by slemonide** [comment]
@sofar what is the right way to design an API?

**Comment by sofar** [comment]
Nodes already are an object in the game, so you should use the methods that come with it.

You don't ```minetest.add_text(node)``` if there's already a meta storage for text in the node.

Something like ```meta::set_string("infotext", <string>)``` makes much more sense, plus it's already present and working.

The lua side of this problem isn't the problem either. This has to be coded in the core engine instead.

**Comment by bell07** [comment]
The current implementation with cached textures is optimized for most cases. The use-cases the dynamic textures needed are rare so the enhancement implementation should not affect the current implementation in runtime.

My proposal: Add support for new texture modifier `PNG[escaped-png-binary-data]`
This way it is possible to dynamic reload a specific file without any cache operations:
`local texture = 'PNG['..minetest.escape(f:read("*all"))..']'`

To get more use-cases maybe additional functions to create the texture modifier

`local texture = core.texture_merge_to_png( very_long_dynamic_buid_nested_texture_string )`

and maybe

`local texture = core.formspec_to_png( formspec_string )`

and maybe

creating textures from scratch using primitives (like http://astroa.physics.metu.edu.tr/MANUALS/ImageMagick-6.2.5/www/magick-vector-graphics.html#primitives)

**Comment by paramat** [comment]
Duplicate of #36

**Comment by rubenwardy** [comment]
It isn't - the texture system is separate to the item def one (although there are item def caches for textures)

**Comment by paramat** [comment]
Hmm, well #36 specifically only asks for the ability to change texture in-game, which is identical to this request, so that includes this. Whether changing textures can be done another way can be dealt with in #36.

**Comment by bell07** [comment]
The #36 is about replace „texture.png“ by „texture2.png“. This one is about reloading the Content of „texture.png“

**Comment by paramat** [comment]
#36 has become about something different yes, but only later. The first post only asks, in a basic way, for a way to change textures in-game, that is identical to this request. The first posts are:

> Allow server-side mod code to modify textures at runtime, i.e. replace an already-loaded texture with new image file content. If feasible, also allow loading new textures,

> Now only meta data of the node can be changed in real-time. But to change property such as texture you need to remove node from the world and place another node with desired property on the same place.

So this request should have been closed as a duplicate.

**Comment by paramat** [comment]
It does, nevermind the use example. #36 is:
> Now only meta data of the node can be changed in real-time. But to change property such as texture

== 'change texture in real time'

This request is:
> modify textures at runtime ... also allow loading new textures

== 'modify / load textures at runtime'
These are clearly identical.

**Comment by Lejo1** [comment]
What about adding to late-loaded files .nonauto so: wool_pink.png.nonauto.
Then we just need to add a function to late send this media.

**Comment by DeltaF1** [comment]
I was about to start designing a mod that generates unique node types per world. Part of that includes generating textures and saving them for later usage. Does the existence of this issue mean that there is no way to save textures dynamically at the moment?

**Comment by sfan5** [comment]
#9961 has been merged and allows loading new textures at runtime. This solves usecase 1 from the request.

**Comment by Warr1024** [comment]
> A player skins mod, allowing players to customize their skins individually.

Yep, solved.

>Signs mods, allowing custom text (without creating a ton of individual entities) and/or custom graphics and styling on signs.

This is now possible using external code to render the signs to images.  It could be done with os.execute(), or an HTTP backend, or something.  Not exactly "solved" but a major obstacle has definitely been cleared.

For signs in particular, having good unicode support is challenging (infeasible to use a bitmap font) with a project that has a significant non-latin-alphabet-using community like Minetest.  Having a texturemod or something to draw text with good freetype/unicode support would help a lot, by allowing this to be done without external support.

As it is now, though, it's probably feasible to do custom signs on a server, at least, where the server admin has control over the config and enough scripting/modding knowledge to glue something together.

> Changing global appearance of nodes without changing nodedefs, such as for a "seasons" mod that might change global leaves/grass colors over time.

I think when I originally wrote this I was thinking about the scenario where you can use custom-loaded textures to _replace_ existing named textures, and have visuals rebuilt to use the updated graphics.  This seems like it'd be hard to do without breaking caching in other important ways, and maybe not worth it after all...

**Comment by Warr1024** [comment]
> For signs in particular, having good unicode support is challenging (infeasible to use a bitmap font) with a project that has a significant non-latin-alphabet-using community like Minetest. Having a texturemod or something to draw text with good freetype/unicode support would help a lot, by allowing this to be done without external support.

Oh, it turns out that I forgot I already filed this one myself ... #9946

**Comment by Sokomine** [comment]
Sofar wrote:
> As for signs, I'm convinced that signs should be rendered client-side. All the bits needed are already in the code. The client knows what a sign is and could easily use the cguifont/irrlicht support to render font text on the node surface. Other sign like nodes could easily be supported, and this would remove the need to send any new node data over the network, and does not need a protocol change (just an updated client version that supports this).

Sounds like a good plan. Signs are a very important part of the game. I'm not up to date as to how it is implemented now. Something that shows up immediately after/when the mapblock has been rendered would definitely be great. There's also the problem that a larger font size leads to signs beeing partially unreadable.

Sofar wrote:
> As for seasons - this seems like it is something that could be added client-side in the form of shaders or similar, again without requiring any new protocol or API change, other than a way to convene the changing of seasons to a client.
Doing that client-side sounds great as well. The last time I saw a 4seasons mod in action it changed the nodes on the server. That looked very impressive but had drawbacks - many many block changes when just the color of the node changed plus no updates of mapblocks that where too far away.

One point that made the mod very impressive to operate was that it didn't change all nodes immediately but made nodes switch season randomly. Between seasons, about half of the nodes belonged to one season and a random half to the other season.

There won't be any new textures needed for seasons. Perhaps the mapblock could contain metadata information about when each node ought to switch to the next season (version). This value could be determined randomly once the mapblock is generated (or the node placed). The sequence would then be the same for each season, but that's not even unrealistic - some dirt may thaw faster and freeze later than other parts of the land. The server would then only have to send the season-specific time (aka a time that applies to the following nodes: default:dirt_with_grass, default:leaves etc.)

That might even allow for other server-based timers for other nodes to exist, i.e traffic lights, doors opening/closing, secret entrances beeing open only at certain "times" (sometimes the server time-of-day might do), lamps going on automaticly at night...The question is: Can the client handle this? It would have to apply the changes.

Perhaps this ought to be broken up into diffrent issues.

I'm glad that there seems to be a solution for dynamicly loaded skin textures. Skins are extremly important for a lot of players.

**Comment by Sokomine** [comment]
Sofar wrote:
> As for signs, I'm convinced that signs should be rendered client-side. All the bits needed are already in the code. The client knows what a sign is and could easily use the cguifont/irrlicht support to render font text on the node surface. Other sign like nodes could easily be supported, and this would remove the need to send any new node data over the network, and does not need a protocol change (just an updated client version that supports this).

Sounds like a good plan. Signs are a very important part of the game. I'm not up to date as to how it is implemented now. Something that shows up immediately after/when the mapblock has been rendered would definitely be great. There's also the problem that a larger font size leads to signs beeing partially unreadable.

Sofar wrote:
> As for seasons - this seems like it is something that could be added client-side in the form of shaders or similar, again without requiring any new protocol or API change, other than a way to convene the changing of seasons to a client.
Doing that client-side sounds great as well. The last time I saw a 4seasons mod in action it changed the nodes on the server. That looked very impressive but had drawbacks - many many block changes when just the color of the node changed plus no updates of mapblocks that where too far away.

One point that made the mod very impressive to operate was that it didn't change all nodes immediately but made nodes switch season randomly. Between seasons, about half of the nodes belonged to one season and a random half to the other season.

There won't be any new textures needed for seasons. Perhaps the mapblock could contain metadata information about when each node ought to switch to the next season (version). This value could be determined randomly once the mapblock is generated (or the node placed). The sequence would then be the same for each season, but that's not even unrealistic - some dirt may thaw faster and freeze later than other parts of the land. The server would then only have to send the season-specific time (aka a time that applies to the following nodes: default:dirt_with_grass, default:leaves etc.)

That might even allow for other server-based timers for other nodes to exist, i.e traffic lights, doors opening/closing, secret entrances beeing open only at certain "times" (sometimes the server time-of-day might do), lamps going on automaticly at night...The question is: Can the client handle this? It would have to apply the changes.

Perhaps this ought to be broken up into diffrent issues.

I'm glad that there seems to be a solution for dynamicly loaded skin textures. Skins are extremly important for a lot of players.

**Comment by Sokomine** [comment]
Sofar wrote:
> As for signs, I'm convinced that signs should be rendered client-side. All the bits needed are already in the code. The client knows what a sign is and could easily use the cguifont/irrlicht support to render font text on the node surface. Other sign like nodes could easily be supported, and this would remove the need to send any new node data over the network, and does not need a protocol change (just an updated client version that supports this).

Sounds like a good plan. Signs are a very important part of the game. I'm not up to date as to how it is implemented now. Something that shows up immediately after/when the mapblock has been rendered would definitely be great. There's also the problem that a larger font size leads to signs beeing partially unreadable.

Sofar wrote:
> As for seasons - this seems like it is something that could be added client-side in the form of shaders or similar, again without requiring any new protocol or API change, other than a way to convene the changing of seasons to a client.
Doing that client-side sounds great as well. The last time I saw a 4seasons mod in action it changed the nodes on the server. That looked very impressive but had drawbacks - many many block changes when just the color of the node changed plus no updates of mapblocks that where too far away.

One point that made the mod very impressive to operate was that it didn't change all nodes immediately but made nodes switch season randomly. Between seasons, about half of the nodes belonged to one season and a random half to the other season.

There won't be any new textures needed for seasons. Perhaps the mapblock could contain metadata information about when each node ought to switch to the next season (version). This value could be determined randomly once the mapblock is generated (or the node placed). The sequence would then be the same for each season, but that's not even unrealistic - some dirt may thaw faster and freeze later than other parts of the land. The server would then only have to send the season-specific time (aka a time that applies to the following nodes: default:dirt_with_grass, default:leaves etc.)

That might even allow for other server-based timers for other nodes to exist, i.e traffic lights, doors opening/closing, secret entrances beeing open only at certain "times" (sometimes the server time-of-day might do), lamps going on automaticly at night...The question is: Can the client handle this? It would have to apply the changes.

Perhaps this ought to be broken up into diffrent issues.

I'm glad that there seems to be a solution for dynamicly loaded skin textures. Skins are extremly important for a lot of players.

**Comment by Sokomine** [comment]
Sofar wrote:
> As for signs, I'm convinced that signs should be rendered client-side. All the bits needed are already in the code. The client knows what a sign is and could easily use the cguifont/irrlicht support to render font text on the node surface. Other sign like nodes could easily be supported, and this would remove the need to send any new node data over the network, and does not need a protocol change (just an updated client version that supports this).

Sounds like a good plan. Signs are a very important part of the game. I'm not up to date as to how it is implemented now. Something that shows up immediately after/when the mapblock has been rendered would definitely be great. There's also the problem that a larger font size leads to signs beeing partially unreadable.

Sofar wrote:
> As for seasons - this seems like it is something that could be added client-side in the form of shaders or similar, again without requiring any new protocol or API change, other than a way to convene the changing of seasons to a client.
Doing that client-side sounds great as well. The last time I saw a 4seasons mod in action it changed the nodes on the server. That looked very impressive but had drawbacks - many many block changes when just the color of the node changed plus no updates of mapblocks that where too far away.

One point that made the mod very impressive to operate was that it didn't change all nodes immediately but made nodes switch season randomly. Between seasons, about half of the nodes belonged to one season and a random half to the other season.

There won't be any new textures needed for seasons. Perhaps the mapblock could contain metadata information about when each node ought to switch to the next season (version). This value could be determined randomly once the mapblock is generated (or the node placed). The sequence would then be the same for each season, but that's not even unrealistic - some dirt may thaw faster and freeze later than other parts of the land. The server would then only have to send the season-specific time (aka a time that applies to the following nodes: default:dirt_with_grass, default:leaves etc.)

That might even allow for other server-based timers for other nodes to exist, i.e traffic lights, doors opening/closing, secret entrances beeing open only at certain "times" (sometimes the server time-of-day might do), lamps going on automaticly at night...The question is: Can the client handle this? It would have to apply the changes.

Perhaps this ought to be broken up into diffrent issues.

I'm glad that there seems to be a solution for dynamicly loaded skin textures. Skins are extremly important for a lot of players.

**Comment by Emojigit** [comment]
In theory, node definitions (use case 3) should be able to read textures sent dynamically. However, the rendering of node tiles are usually before the time the dynamically sent texture is ready. Therefore, this results in a dummy image for the normal tile, and regular images for the cracking images (as they are generated on demand). This should be solved by rebuilding texture caches upon the arrival of related dynamic media.

**Comment by Wuzzy2** [comment]
Is this issue already solved with `minetest.dynamic_add_media`?

**Comment by appgurueu** [comment]
> Is this issue already solved with `minetest.dynamic_add_media`?

Not entirely. Dynamic media lets you add media, but it doesn't let you update it.

**Comment by MisterE123** [comment]
I need to create a custom minimap. I have a large image of an area of map, which I cut down to a view size around the player's location using [combine. Next, I put various custom indicators on the minimap such as a circle indicating a wall of death and other player markers and pois.

I can't use the regular minimap because it doesn't show un-sent or unloaded mapblocks, and because it doesn't support custom markers. In this usecase, the entire play area has already been generated and the minimap image saved.

of course, this uses alot of texture modifiers which are resent on the globalstep to update the hud, which rapidly consumes ram since none of these large images are ever unloaded.

There does not seem to be any reasoable alternatives either: building the minimap out of small movable parts would require a thick ugly border to hide the jank.
![image_20240726094333](https://github.com/user-attachments/assets/4aaccfaa-2ce2-48b1-8f08-50096990597d)

**Comment by jingkaimori** [comment]
This feature does not resolve rendering issue of signs completely. AFAIK texture of node is shared between __all__ of node which has the same node id and param2. But signs with the same node id may contain different text. Range of param2 is also extremely small compared to range of text appears on signs. If rendering text directly with node surface, number of paragraphs on sign is restricted by node id.

display_modpack solves the issue by adding an entity to carry texture which may changed dynamically. To avoid entity used here, a mechanism to override texture defined by nodedef with information from certain node such as node metadata can help.

**Comment by appgurueu** [comment]
A thought: Textures in particular are comparatively hard to do properly (as in: a lot of work) because they're everywhere. But translations, fonts, models, and perhaps even sounds could be much easier to do.
