### ISSUE TITLE
Why is not /usr/share/minetest/mods recognized on Linux?

### ISSUE THREAD

**Issue by shellkr** [minetest/minetest#3597]
I have an issue I don't know how to solve. I am making packages for a couple of mods on Arch Linux so they are easy to install. I install them to the default directory /usr/share/minetest/mods but it is like they are not recognized. I then move them to ~/.minetest/mods and it works. The home folder is not a global directory on Linux but a per user directory and it should thus not be treated like one.

Why are /usr/share/minetest/mods not recognized?

The problem when making a package is that you cannot install them directly to ~/.minetest/mods without breaking standards. I have to add post install instructions that inform the user to manually move the mod folders to ~/.minetest/mods directory. That is not a clean way to do it and completely unnecessary.

**Comment by celeron55** [comment]
So, first things first: lua_api.txt does list `$path_share/mods/` as a mod load path: https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L84

If you run something like `bin/minetest --info --run-unittests 2>&1 | grep Detected`, does it say `Detected share path: /usr/share/minetest/`?

There's a check here that if the game is user-installed, then globally installed mods will not be available. Is this what is happening?: https://github.com/minetest/minetest/blob/master/src/subgame.cpp#L114

**Comment by ShadowNinja** [comment]
@celeron55: Why don't we search the global mod path if the game is loaded from a user-specific directory?

**Comment by shellkr** [comment]
@celeron55 Yes, I saw it which is why I ask. It seems strange it doesn't work. I asked on IRC and someone there said it was intentional.

It does..

    2016-01-23 23:56:53: INFO[Main]: Detected share path: /usr/share/minetest
    2016-01-23 23:56:53: INFO[Main]: Detected user path: /home/shellkr/.minetest 
    2016-01-23 23:56:53: INFO[Main]: Detected cache path: /home/shellkr/.cache/minetest

The game is installed to /usr/ by root (i.e. via the package manager and sudo). I am not sure what you mean with user-installed. This is the build receipt used to make the package that I install https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=minetest-git.

**Comment by celeron55** [comment]
@ShadowNinja I don't know. That check probably dates back to the origins of 0.4 and might have been just a guess about what might make sense in the long run.

**Comment by everamzah** [comment]
Debian has moreblocks, moreores, and pipeworks.  It places them in /usr/share/games/minetest/mods.

**Comment by shellkr** [comment]
I think I have found the reason to part of the problem. I looked in the root where compiling instructions are and found this...

    - If you want to install it system-wide (or are making a distribution package),
    you will want to use -DRUN_IN_PLACE=FALSE

So the reason seems to be that it is "user-installed" as the above option is not set in the package I use. A potential miss by the package manager I guess... But why is this necessary? Wouldn't it be better if it defaulted to -DRUN_IN_PLACE=FALSE ?

**Comment by ShadowNinja** [comment]
Although this is solved, I'd like to know why the user-installed-global-skipping code is there -- or just have it removed.

**Comment by shellkr** [comment]
I think I may have been to quick in proclaiming this solved. Perhaps cache or a race condition was in play because now it doesn't work again. No mods are detected in /usr/share/minetest/mods.

    /usr/bin/minetest --info
    2016-01-25 08:26:13: INFO[Main]: Using system-wide paths (NOT RUN_IN_PLACE)
    2016-01-25 03:26:13: INFO[Main]: Detected share path: /usr/share/minetest
    2016-01-25 03:26:13: INFO[Main]: Detected user path: /home/shellkr/.minetest
    2016-01-25 03:26:13: INFO[Main]: Detected cache path: /home/shellkr/.cache/minetest
    2016-01-25 03:26:13: ERROR[Main]: Couldn't find a locale directory!
    2016-01-25 03:26:13: INFO[Main]: minetest with SER_FMT_VER_HIGHEST_READ=26, VER=0.4.13-dev-735e3b7-dirty 
    BUILD_TYPE=Release RUN_IN_PLACE=0 USE_GETTEXT=0 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 
    USE_LUAJIT=0 STATIC_SHAREDIR="/usr/share/minetest"

**Comment by shellkr** [comment]
Do I have to open a new issue? This shouldn't be closed until it is solved.

**Comment by shellkr** [comment]
Could someone open this issue again? It is still not solved... or do I have to open a new one?

**Comment by shellkr** [comment]
I first rolled back a couple of iterations but no success... I then checked the patch from Debian, applied it and it works...

http://anonscm.debian.org/cgit/pkg-games/minetest-v04x.git/tree/debian/patches/shared_mods.patch

I am guessing they didn't send it upstreams? Will you include this?

**Comment by shellkr** [comment]
Any words on this? Depending on how you decide to continue I can continue. Right now I am not sure if I should patch all my packages or not.

**Comment by Rencer** [comment]
Today it's 2017, May 10 and I freshly installed Minetest and some mods from the AUR repo, under the Arch-based Manjaro Linux.
This issue is still there, the mods are not recognised from /usr/share/minetest/mods.

In the AUR repo there is a package called "minetest-usrdir_patch"
("A patch and a pacman-hook to fix a bug in Minetest not dicovering /usr/share/minetest")
This package is suggested by some mods when you install them, because without it the game unable to recognised the mods in the default /usr/share/minetest/mods install directory.
I installed it before I installed the mods, but this patch does not work, the mods still not recognised.
This issue is look like a serius bug, because it affect all the mods.

Why the mod makers have to warn the users about this annoying nonsense issue? 
Just asking, because after reading all the posts here, it looks very simple to fix it by the minetest programmers. (Or whoever need to take care of it...)
Like, why not just simply all the mods (and the game itself!) by default, installed to the "Detected user path" and not in a folder that require root privileg to access it? It make no sense.
If I simply copy all the mod inside my /.mietest/mods folder, the game recognise them, so it looks like this is the default path where the game search for it, and not where the mods are installed by the package manager. So it really make no sense, why the "usr/share" folder is used at all.

I really hope it finally be fixed soon.

Keep up the great work guys, and million thanks for this great game!!!

**Comment by shellkr** [comment]
@Rencer The $HOME is not a place where you install packages... The standard is to put them in /usr. It is done the same in other distros. I think they all patch it. In Arch you often keep the software default so that it turns out as the creator have intended. Which means the patch has to be applied post-install when you install a mod. It is a hook for the package manager and should be reapplied every time you install/update Minetest via pacman. I know Manjaro forked pacman and don't know their current status if they support hooks. 

I am the creator of that usrdir_patch package and most of the mods.. so I am interested to help where I can.

**Comment by nerzhul** [comment]
I think i will look at the mod loading code and add this option on Linux/BSD

**Comment by mortlind** [comment]
Sorry if this is off-topic: I have tried to find out where minetestserver will look for mods that did not come with the distribution (Debian). I would like to dump these mods someplace else than in the distribution's mods directory, and these mods are not associated with some users ~/.minetest, it is on a server, launched with systemd, and running under the homeless user Debian-minetest. I do not find documentation on where site-mods are to be installed. Could someone point me in the right direction. Thanks in advance.

**Comment by mpan-pl** [comment]
The issue doesn’t occur on Arch Linux with the current version (0.4.17.1). See the attachment. Changing `RUN_IN_PLACE` unser Arch Linux is also unneccessary, as it is already `0`.

Also please note that Manjaro is not Arch Linux. The distro share the package manager (pacman) and this is the end of similarities. Therefore the issue should not be traced as Arch-related, unless — of course — someone shows that the issue occurs in the current version of Arch Linux.
