### ISSUE TITLE
object:punch(puncher, ... should allow nil for puncher

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#3837]
But, the code handling this is written as follows:

```
        ObjectRef *ref = checkobject(L, 1);
        ObjectRef *puncher_ref = checkobject(L, 2);
        ServerActiveObject *co = getobject(ref);
        ServerActiveObject *puncher = getobject(puncher_ref);
        if (co == NULL) return 0;
        if (puncher == NULL) return 0;
```

ergo, if `puncher == nil`, no punch is delivered.

The API clearly states in several places that `nil` is allowed. And this would be useful for mods to add "environment" damage that isn't attributable to objects.

It also is valid that the event punch `on_punch(puncher, ...` is then called with `nil` as puncher, and again the API documentation states that that is valid as well.

**Comment by C1ffisme** [comment]
:+1:

**Comment by gejan** [comment]
This should be fixed since 2013: https://github.com/minetest/minetest/commit/55a97f4605a263f4b670b447cd4af9ffa1a8d472

**Comment by sfan5** [comment]
I don't know when the code in the linked commit was removed, but this is currently not working as described.
https://github.com/minetest/minetest/blob/5c9983400fb085167bf11f8a0483b8e8f6dd8a24/src/script/lua_api/l_object.cpp#L171-L174

**Comment by sofar** [comment]
The whole original problem is that `!puncher` should not be a reason to `return 0`. Instead, when `!puncher`, the code below the statement should execute.

This hasn't changed, someone just simplified the code, but it still does not call
`co->punch(dir, &toolcap, puncher, time_from_last_punch);` with `puncher == NULL` as it probably should.

**Comment by sfence** [comment]
There is a code

https://github.com/minetest/minetest/blob/92c55c27cf520bd7b0e59639cc7cce7bcaf5d747/src/server/player_sao.cpp#L462

for players and similar

https://github.com/minetest/minetest/blob/92c55c27cf520bd7b0e59639cc7cce7bcaf5d747/src/server/luaentity_sao.cpp#L329

for Lua entities.

So, is this only a documentation issue, or what is expected from punch methods to do, if the puncher is `nullptr`?
