### ISSUE TITLE
Cannot move after a few seconds (OS X, brew)

### ISSUE THREAD

**Issue by brabalan** [minetest/minetest#4274]
After a few seconds, I can no longer move nor jump. I can still look around using the mouse, and the game has not crashed.

I'm using OS X El Capitan, and I installed the current version of Minetest with Homebrew. I tried to set the debug level to 4 but I cannot see anything strange in the debug file.

I also reported this on the forums, and others said they can reproduce it: https://forum.minetest.net/viewtopic.php?f=6&t=15057

**Comment by Wayward1** [comment]
I believe I have encountered this as well (or at least something similar), quite a few times. Random servers, random times, when I join I can look around but not move. A simple relog fixes the problem.
Linux Mint 17.3

**Comment by brabalan** [comment]
Unfortunately relogging fixes the problem, but only for a few seconds.

**Comment by echosa** [comment]
I'm having this issue as well. I mentioned it here: https://github.com/minetest/minetest/issues/2697#issuecomment-240287374

**Comment by echosa** [comment]
This issue keeps Minetest from being playable on Mac. I've switched to the minimal dev game, turned off all the main options on the Settings page like shaders, smooth lighting, etc. I turned the logging level to verbose. I still have this issue and see nothing in the logs. When I run the game from the command line with `--info --verbose`, I don't see anything useful either. I have no idea what's causing this issue, but I also don't have any idea how to start trying to find out. Are there any other logs that are kept? Is there any other way to figure out what's going on? I've been able to play a bit on Windows 10, once I got it working there, and I enjoy the game. Not being able to play on OS X, though, is very unfortunate, as I'm rarely logged into Windows.

**Comment by brabalan** [comment]
I gave the nightly from https://github.com/krondor-game/minetest/releases a try and it works great. As the issue also arises from the stable version from there, I assume it has been fixed in the intervening commits, and homebrew will start working again when a new version is out. In the meantime I recommend using the nightly build.

**Comment by echosa** [comment]
@brabalan Oh, cool. I'll give that a shot when I get a chance!

**Comment by echosa** [comment]
Interesting... when I use the krondor-game version, the games seems to run fine. (Which is awesome!) However, when I install through homebrew, even if I install the latest code with `brew install minetest --HEAD`, I still have the problem.

So, what's different about krondor-game's version that makes it work? Or, rather, what's different about the brew built version that makes it _not_ work?

**Comment by echosa** [comment]
I've asked about this on the forum page for the krondor releases: https://forum.minetest.net/viewtopic.php?f=42&t=9190&p=234545#p234545

**Comment by neoascetic** [comment]
Reproducible even for Krondor's nightly (i. e. latest) builds. Bad. It means we don't have the freshest playable version of minetest for OSX now.

**Comment by neoascetic** [comment]
Okay, I've found something. The latest playable version I have under my hand [was built under OSX10.9](https://travis-ci.org/krondor-game/minetest/builds/164428449#L4). And the latest available (and thus unplayable) version was [built under OSX10.11](https://travis-ci.org/krondor-game/minetest/builds/178634314#L4). This explains why we have the issue when building using homebrew (I guess most users has Sierra or at least El Capitan installed). Thus, this is some OS-related issue and we need to dig in that direction.

**Comment by echosa** [comment]
I can confirm I've been using El Capitan the whole time.

**Comment by brabalan** [comment]
Same here, using El Capitan.

**Comment by neoascetic** [comment]
Is there someone with 10.9 to test if it's OSX's issue or Irrlicht's?

**Comment by neoascetic** [comment]
Even if there are no blocks under the character it does not fall. It means that this is actually player's physics simulation problem and not something related to keyboard input. Appears in singleplayer as well.

**Comment by echosa** [comment]
I do not have access to any OS X prior to El Capitan. Maybe a VM would suffice, though?

**Comment by ScrambledAuroras** [comment]
Also note that fast_move seems to not work. I think that might be a config issue though.

**Comment by nigels-com** [comment]
Same problem here on Mac 10.12.2 (Sierra) and brew minetest 0.4.14.  Some keys work, such as digging blocks, including those below the player.

**Comment by kencu** [comment]
For a data point, I just built minetest 0.4.14 using macports and irrlicht 1.8.4 on MacOS 10.6, and it also has the 'no movement' after a few moments use issue. No error messages so far to give a clue as to why. Some keys still work, but not w/a/s/d.  Will see if I can help figure out what's going on.

**Comment by kencu** [comment]
Changing the build type to RelWithDebInfo instead of Release seems to fix the movement problem, at least on the Macports version I'm working on. This is on 10.6, and also on 10.12. Setting build type to Debug fixed it too, but with some extra detail left on the screen.

**Comment by nigels-com** [comment]
Might be worth valgrinding minetest on Linux, to see how healthy things are in terms of unintialised memory reads.  (UMR)

**Comment by scfarley** [comment]
I am also experiencing this with FreeBSD 11.0-STABLE (r310303).  I did not see it with FreeBSD 10-STABLE (at least 10.3).  I turned off all the port options without any luck.

However, I was successful when compiling with gcc v6 instead of clang (3.8 or 3.9).  It could be a bug with clang, or there is a bug in the minetest code that is only noticeable when built by clang.  This is presuming that macports uses clang.

**Comment by kencu** [comment]
macports with clang appears to work great with any target other than "Release".

**Comment by nigels-com** [comment]
I was hoping to reproduce this on Ubuntu 16.04 with clang/clang++ toolchain, but no luck.  Valgrind seems clean, overall.

**Comment by neoascetic** [comment]
I can confirm that this doesn't happen in Debug build type. I'll switch krondor-game releases to this type for now, but I hope someone will find the real problem.

**Comment by kencu** [comment]
@nigels-com 
We also have valgrind on macports, but I don't have much experience using it. If you give me a couple of pointers on how to get started with using it to examine minetest, I'll see what it comes up.

**Comment by kencu** [comment]
I think I may have found the problem.

In src/CMakeLists.txt there is a section on various optimization flags set for various releases. In there, there is this bit `	set(CMAKE_CXX_FLAGS_RELEASE "-DNDEBUG ${RELEASE_WARNING_FLAGS} ${WARNING_FLAGS} ${OTHER_FLAGS} -ffast-math -Wall -pipe -funroll-loops")`

deleting the `-ffast-math` flag (prior to the build, 'natch) appears to fix the movement problem even with the release build selected. 

Looking around on the web, there are a number of examples of ffast-math bugs in clang mentioned, so this would make sense. Try it out on other systems, and if we find that fixes it for everyone, we can submit it to the minetest devs for consideration.

**Comment by kencu** [comment]
looks like minetest 0.4.15 has the same behaviour. The same movement issue comes when playing the release version, and deleting the -ffast-math flag fixes it. So I've incorporated that patch into the macports version pending the minetest source to address it.

**Comment by echosa** [comment]
Can that same patch (or similar) be added the the homebrew forumula?

**Comment by kencu** [comment]
I'm not sure how to do that (I should learn more about homebrew, seems like a lot of nice people there) --  but the fix itself, assuming it works as well for others as it does here on this system, is quite a simple one -- just delete that one optimization flag from src/CMakeLists.txt.

**Comment by nigels-com** [comment]
I'm no Ruby wizard, but I'm poking about in the brew formula. `brew edit minetest` . It has two modes: *stable* (which I'm updating from 0.4.14 to 0.4.15) and *head* which appears to be from github master branch.  Ideally the CMakeLists.txt would support a flag for opting in our out of --ffast-math.

```
$ brew upgrade minetest
==> Upgrading 1 outdated package, with result:
homebrew/games/minetest 0.4.15
==> Upgrading homebrew/games/minetest 
==> Downloading https://github.com/minetest/minetest/archive/0.4.15.tar.gz
==> Downloading from https://codeload.github.com/minetest/minetest/tar.gz/0.4.15
######################################################################## 100.0%
==> Downloading https://github.com/minetest/minetest_game/archive/0.4.15.tar.gz
==> Downloading from https://codeload.github.com/minetest/minetest_game/tar.gz/0.4.15
######################################################################## 100.0%
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/minetest/0.4.15 -DCMAK
==> make package
==> unzip minetest-*-osx.zip
==> Caveats
...
==> Summary
🍺  /usr/local/Cellar/minetest/0.4.15: 944 files, 33.6M, built in 2 minutes 53 seconds
```

**Comment by nigels-com** [comment]
Brew *master* branch build using `--HEAD`:

```
$ brew install --HEAD minetest
==> Installing minetest from homebrew/games
==> Cloning https://github.com/minetest/minetest.git
Cloning into '/Users/nigels/Library/Caches/Homebrew/minetest--git'...
remote: Counting objects: 1033, done.
remote: Compressing objects: 100% (913/913), done.
remote: Total 1033 (delta 128), reused 524 (delta 63), pack-reused 0
Receiving objects: 100% (1033/1033), 8.47 MiB | 1.64 MiB/s, done.
Resolving deltas: 100% (128/128), done.
==> Checking out branch master
==> Cloning https://github.com/minetest/minetest_game.git
Cloning into '/Users/nigels/Library/Caches/Homebrew/minetest--minetest_game--git'...
remote: Counting objects: 640, done.
remote: Compressing objects: 100% (579/579), done.
remote: Total 640 (delta 69), reused 527 (delta 47), pack-reused 0
Receiving objects: 100% (640/640), 1.36 MiB | 320.00 KiB/s, done.
Resolving deltas: 100% (69/69), done.
==> Checking out branch master
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/minetest/HEAD-a95f983 
==> make package
...
```

**Comment by nigels-com** [comment]
I filed a pull request for homebrew-games minetest formula: 
https://github.com/Homebrew/homebrew-games/pull/757

The fix removes the -ffast-math flag in the CMakeLists.txt

**Comment by scfarley** [comment]
Removing -ffast-math from the release build fixes minetest when built with Clang v3.8 on FreeBSD.  I have opened a bug with a fix for FreeBSD ports:  https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=215532

**Comment by neoascetic** [comment]
Actually, the issue appears even with GCC, so it isn't only Clang's issue.

**Comment by neoascetic** [comment]
Should `-ffast-math` be disabled within minetest repo for OSX and FreeBSD?

**Comment by nigels-com** [comment]
We think it's clang-specific.  I'll go try repo it with gcc (assuming there is a brew gcc I can bring to the Mac).  I guess so far the logic would be to omit `-ffast-math` for both Mac and FreeBSD.  Or enable it only for Linux, perhaps.

**Comment by neoascetic** [comment]
It **isn't** clang-specific on OSX.

**Comment by nigels-com** [comment]
@neoascetic Do you have any suggestions for gcc toolchain on Sierra?  brew gcc-6 seemed to choke on CoreFoundation headers.

**Comment by neoascetic** [comment]
My bad, I was building minetest on travis and it seems [that you need more steps](https://github.com/travis-ci/travis-ci/issues/2423) than just specify `compiler: gcc` in the `.travis.yml`.

Anyway, I was unable to build minetest with GCC because of all those `error: 'introduced' was not declared in this scope` errors (see log [here](https://travis-ci.org/krondor-game/minetest/builds/186509354)).

So, maybe it **is** clang-specific issue after all.

**Comment by nigels-com** [comment]
The brew patch has been accepted and merged.
Works for me on Sierra.

```
$ brew uninstall minetest
Uninstalling /usr/local/Cellar/minetest/0.4.15... (944 files, 33.6M)
$ brew install minetest
==> Installing minetest from homebrew/games
==> Downloading https://homebrew.bintray.com/bottles-games/minetest-0.4.15.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring minetest-0.4.15.sierra.bottle.tar.gz
==> Caveats
...
==> Summary
🍺  /usr/local/Cellar/minetest/0.4.15: 944 files, 33.6M
$
```

The logic I'd suggest for Minetest CMakeLists.txt would be to make `-ffast-math` an opt-in.

**Comment by kencu** [comment]
You could also wrap it in an 'if gcc' block.

**Comment by kencu** [comment]
You could also add the --fast-math flag only if the compiler is gcc. Cmake can do this pretty easily.

**Comment by nigels-com** [comment]
It would need some testing.  Out of the box clang *pretends* to be gcc, so we'd want to be sure that cmake is sure that it *really* is gcc, and not just a pretender.

**Comment by sfan5** [comment]
clang with `-ffast-math` works fine on Linux, so always disabling it isn't a solution.

**Comment by kencu** [comment]
hey, that's interesting. clang with fast-math fails on MacOS and FreeBSD (apparently) but works on linux. Now I wonder exactly why that would be?... curious. You would think the fast-math macros would work the same on all three platforms...

**Comment by nigels-com** [comment]
Possibly concerning `sqrt`
https://llvm.org/bugs/show_bug.cgi?id=24063

**Comment by Zeno-** [comment]
One of the things that fast-math (in addition to what nigels-com pointed out) can do that will not happen (ever) on floating point expressions is re-arrange or simplify them. This would normally just potentially introduce precision errors (and why without fast-math the compiler will never re-arrange floating point operations[1]). That in itself seems to be unlikely to cause a crash, but it's possible.

[1] I think the C++ Standard actually says that the compiler is not allowed to without the user expressly telling it to using e.g. a switch like fast-math

**Comment by AraHaan** [comment]
Please install g++-6 for the projects that use C++ 14~17, besides it has some bug fixes and some performance fixes as well.

Example being like this especially clang 3.9 requirements on projects fails when someone uses ``std::experimental::filesystem`` in the ``<experimental/filesystem>`` header in C++ 14, in C++ 17 it will move to ``std::filesystem`` and the header would be renamed to ``<filesystem>``

https://travis-ci.org/AraHaan/bin2c/builds/188047806 As you can see all the OSX builds fail because clang 3.9 and g++-6 are not present. But the gcc 6 build of it on linux works just fine. Note: I try to manually hack the compilers and the clang version to 3.9 using the build matrix method.

Besides a lot of projects requires g++-6, gcc-6, and clang 3.9 only to build and any versions before that would be no dice.

**Comment by Thomas--S** [comment]
I installed minetest with homebrew on my MacBook again today, and I can confirm that the problem seems to be fixed.

**Comment by paramat** [comment]
@brabalan please can you test for the bug again?

**Comment by brabalan** [comment]
Everything is now working, so I'm closing the issue.

**Comment by vlapsley** [comment]
The issue is fixed using Homebrew, but the bug remains when compiling from source.

**Comment by neoascetic** [comment]
@vlapsley exactly, because Homebrew's formula [patches build instructions](https://github.com/Homebrew/homebrew-core/blob/master/Formula/minetest.rb#L53) in order to avoid the bug. IMO the bug wasn't resolved, that was just a workaround.

**Comment by nigels-com** [comment]
Yes, confirming the issue is still there for a vanilla cmake build from master branch.
The brew installed minetest is fine.
