### ISSUE TITLE
map_generation_limit trigger server crash

### ISSUE THREAD

**Issue by 00c** [minetest/minetest#4923]
map_generation_limit is a bit offset, any active object outside limit cause server crash, falling snow mobs selecting area with WorldEdit and so on.

> 2016-12-18 09:58:56: ACTION[Server]: Evil digs default:stone at (4511,13,469)
2016-12-18 09:58:56: ERROR[Server]: ServerEnvironment::addActiveObjectRaw(): object position (45110,140,4690) outside maximum range
[biome_lib] Stand by, playing out the rest of the aircheck mapblock log
(there are 0 entries)...
[biome_lib] Stand by, playing out the rest of the no-aircheck mapblock log
(there are 0 entries)...

> 2016-12-18 09:58:59: ERROR[Main]: ServerError: Lua: Runtime error from mod '*builtin*' in callback node_on_dig(): /home/mt/bin/../builtin/game/falling.lua:116: attempt to index local 'obj' (a nil value)
> 2016-12-18 09:58:59: ERROR[Main]: stack traceback:
> 2016-12-18 09:58:59: ERROR[Main]:       /home/mt/bin/../builtin/game/falling.lua:116: in function 'spawn_falling_node'

> 2016-12-18 09:58:59: ERROR[Main]:       /home/mt/bin/../builtin/game/falling.lua:176: in function 'check_single_for_falling'
> 2016-12-18 09:58:59: ERROR[Main]:       /home/mt/bin/../builtin/game/falling.lua:231: in function 'check_for_falling'
> 2016-12-18 09:58:59: ERROR[Main]:       /home/mt/bin/../builtin/game/falling.lua:269: in function 'callback'
> 2016-12-18 09:58:59: ERROR[Main]:       /home/mt/bin/../builtin/game/item.lua:518: in function </home/mt/bin/../builtin/game/item.lua:443>
> 2016-12-18 09:58:59: ERROR[Main]:       (tail call): ?

**Comment by rubenwardy** [comment]
I found that map_generation_limit causes v7 to crash - does v7 assume a whole sector will generate?

**Comment by 00c** [comment]
I run mt 0.4.14-dev around week old. mgen V6

**Comment by paramat** [comment]
> I found that map_generation_limit causes v7 to crash - does v7 assume a whole sector will generate?

No, mgv7 works essentially the same way as mgv5, flat, fractal and valleys.

**Comment by Rogier-5** [comment]
I can't reproduce this, but have got a patch that does more strict and more accurate checking of map limits. It might solve your problem. If it does, I'll create a PR. See https://github.com/Rogier-5/minetest/tree/map-limit

**Comment by paramat** [comment]
We'll consider your PR after release.

**Comment by 00c** [comment]
How to reproduce:
Disable map_generation_limit, create some areas outside map_generation_limit, then enable it again. 
On some edges map will be loaded outside map_generation_limit. 

Rogie-5 I try that patch, there was snow above leave no changes.

> 2016-12-20 08:08:19: ACTION[Server]: Evil digs snow:leaves at (4511,17,-12)
2016-12-20 08:08:19: ERROR[Server]: ServerEnvironment::addActiveObjectRaw(): object position (45110,180,-120) outside maximum range
2016-12-20 08:08:19: INFO[Main]: Players:

> 2016-12-20 08:08:19: INFO[Main]: Server: Threads stopped
2016-12-20 08:08:20: INFO[Main]: ServerMap: Written: 0 sector metadata files, 793 block files, 1166 blocks in memory.
2016-12-20 08:08:20: INFO[Main]: ServerMap: Blocks modified by: 
2016-12-20 08:08:20: INFO[Main]:   Timestamp expired (step): - - - - - - - - 299
2016-12-20 08:08:20: INFO[Main]:   addActiveObjectRaw, deactivateFarObjects: Static data changed considerably: 1
2016-12-20 08:08:20: INFO[Main]:   addActiveObjectRaw, removeRemovedObjects/remove: 2
2016-12-20 08:08:20: INFO[Main]:   removeRemovedObjects/deactivate: - - - -  1
2016-12-20 08:08:20: INFO[Main]:   removeRemovedObjects/remove: - - - - - -  5
2016-12-20 08:08:20: INFO[Main]:   setNodeNoCheck: - - - - - - - - - - - - - 8
2016-12-20 08:08:20: INFO[Main]:   setTimestamp: - - - - - - - - - - - - - - 1
2016-12-20 08:08:20: INFO[Main]:   setTimestamp, Timestamp expired (step): - 476
2016-12-20 08:08:20: INFO[Main]: ServerMap: Saved map to /home/mt/bin/../worlds/libertyland
2016-12-20 08:08:20: INFO[Main]: BanManager: saving to /home/mt/bin/../worlds/libertyland/ipban.txt
2016-12-20 08:08:20: INFO[Main]: Server: Deinitializing scripting
2016-12-20 08:08:21: ERROR[Main]: ServerError: Lua: Runtime error from mod '*builtin*' in callback node_on_dig(): /home/mt/bin/../builtin/game/falling.lua:116: attempt to index local 'obj' (a nil value)
2016-12-20 08:08:21: ERROR[Main]: stack traceback:
2016-12-20 08:08:21: ERROR[Main]: 	/home/mt/bin/../builtin/game/falling.lua:116: in function 'spawn_falling_node'
2016-12-20 08:08:21: ERROR[Main]: 	/home/mt/bin/../builtin/game/falling.lua:176: in function 'check_single_for_falling'
2016-12-20 08:08:21: ERROR[Main]: 	/home/mt/bin/../builtin/game/falling.lua:231: in function 'check_for_falling'
2016-12-20 08:08:21: ERROR[Main]: 	/home/mt/bin/../builtin/game/falling.lua:269: in function 'callback'
2016-12-20 08:08:21: ERROR[Main]: 	/home/mt/bin/../builtin/game/item.lua:518: in function </home/mt/bin/../builtin/game/item.lua:443>
2016-12-20 08:08:21: ERROR[Main]: 	(tail call): ?

**Comment by paramat** [comment]
Ah, so only a problem if mapgen limit is inconsistently applied to a world?
When it is made per-world this should be solved then?

**Comment by Rogier-5** [comment]
> We'll consider your PR after release

I wasn't expecting it to be considered earlier. Unless maybe it would solve a blocking issue.
But with @00c's explanation, I also don't think this issue should be blocking.

> create some areas outside map_generation_limit, then enable it again.

My patch should solve that.

> When it is made per-world (which is intended) this should be solved then?

IIUC, with per-world limits, if a world's limit were reduced, the issue could still occur.

**Comment by paramat** [comment]
> with per-world limits, if a world's limit were reduced, the issue could still occur.

Yeah, but that would be altering contents of map-meta.txt, which is asking for trouble.

**Comment by paramat** [comment]
So, map gen limit causes problems, and fixes may take a while, i don't think this should delay the release, can we remove the blocker label?

**Comment by 00c** [comment]
Crash happens with any value. There is no solution?

**Comment by paramat** [comment]
Yeah there will be a solution. I'll investigate this.

**Comment by paramat** [comment]
My initial feeling is this: We should not be throwing errors when an object exists outside the currently set map gen limit, because this limit is not yet per-world and is likely to be accidently changed or even intentionally changed. Even when it is per-world someone may want to change it in map_meta.txt. There is no harm in objects being outside the currently set limit, because the limit may have been reduced intentionally.

**Comment by paramat** [comment]
Here's the commit which checks and throws an error https://github.com/minetest/minetest/commit/f61f817b9c170942a5b3ce3591125c2191645cd0

**Comment by paramat** [comment]
Perhaps the set map gen limit can still be enforced in `RemoteClient::GetNextBlocks` and `blockpos_over_limit(p` so that even if the world exists outside the set value it is not sent.

**Comment by paramat** [comment]
I can't find the issue or PR thread for when `objectpos_over_limit()` was added, anyone know where it is?

**Comment by paramat** [comment]
See #4936

**Comment by paramat** [comment]
@00c if you set the map gen limit do you get world generating outside that limit?

**Comment by paramat** [comment]
Now does this need changing too? it's mentioned in your error message:

```
ServerMapSector *ServerMap::createSector(v2s16 p2d)
{
	/*
		Do not create over-limit
	*/
	const static u16 map_gen_limit = MYMIN(MAX_MAP_GENERATION_LIMIT,
		g_settings->getU16("map_generation_limit"));
	if(p2d.X < -map_gen_limit / MAP_BLOCKSIZE
			|| p2d.X >  map_gen_limit / MAP_BLOCKSIZE
			|| p2d.Y < -map_gen_limit / MAP_BLOCKSIZE
			|| p2d.Y >  map_gen_limit / MAP_BLOCKSIZE)
		throw InvalidPositionException("createSector(): pos. over limit");
```

**Comment by paramat** [comment]
`ServerMap::createSector` is calle dby `ServerMap::emergeBlock` which is called by `ServerEnvironment::addActiveObjectRaw()` so the answer seems to be yes.

**Comment by paramat** [comment]
I doubt i can fix this in time for release, it's very complex.

**Comment by paramat** [comment]
I'm now thinking just change this error to a warning, the object is deleted anyway so no need to halt the game https://github.com/minetest/minetest/blob/master/src/environment.cpp#L1764

**Comment by 00c** [comment]
@paramat i try 2 values 4480 and 4500, on some sides edge is correct, other spots wrong.
map_generation_limit does not work well. It should not load area ( existing or not ) outside limit, somehow it loads on some edges only if that area exist. Lets say i set limit to 4480, map exist till z 5000, player can walk and see map till z 4525.
my conf
> chunksize = 5

Player can walk dig, build in those areas outside limit. But active objects cause crash.

**Comment by 00c** [comment]
I try to delete area outside map_generation_limit with WE, but it cause crash by selecting area.

**Comment by twoelk** [comment]
I sometines use mods to limit the access of players to a map and I almost always precreate content outside the limits. Mostly for optical reasons, it just looks nicer, but sometimes to move the reagion of activity to some other place on the same map. This is pretty usefull to keep a group of kids focused on a project. I can very well imagine that people will try to use  map_generation_limit in a similar way.

**Comment by paramat** [comment]
> i try 2 values 4480 and 4500, on some sides edge is correct, other spots wrong.

it won't be exact, mapgen works in blocks of 16 nodes, so the world will often stop up to 16 nodes before the limit, i'm asking if world is generated beyond the set limit (which it should not), in a newly created world where the limit has been set from the start.

**Comment by paramat** [comment]
Testing n a new world with limit 500, the world stops at -432 or 447, which are mapchunk borders, so only mapchunks entirely within the limit are generated.

**Comment by paramat** [comment]
I fly to 200, restart the world with limit 300, and return to an area which was previously generated, now the world loads to 303, which is over-limit.

**Comment by paramat** [comment]
The 2 other crashes reported are this when a rat spawned:
```
2016-12-17 16:35:07: ERROR[Server]: An unhandled exception occurred: createSector(): pos. over limit
2016-12-17 16:35:07: ERROR[Server]: In thread 7f0cfbd9c700:
2016-12-17 16:35:07: ERROR[Server]: /home/mt/src/server.cpp:73: virtual void* ServerThread::run(): A fatal error occured: createSector(): pos. over limit
```
and this when placing a boat over-limit:
```
2016-12-13 21:31:44: ERROR[Main]: ServerError: Lua: Runtime error from mod 'boats' in callback item_OnPlace(): ...mt/bin/../games/Liberty Land/mods/boats/init.lua:236: attempt to index upvalue 'boat' (a nil value)
2016-12-13 21:31:44: ERROR[Main]: stack traceback:
2016-12-13 21:31:44: ERROR[Main]: ...mt/bin/../games/Liberty Land/mods/boats/init.lua:236: in function <...mt/bin/../games/Liberty Land/mods/boats/init.lua:227>
```
which is probably boat code not finding the boat object because the boat object was not spawned due to being over-limit.

**Comment by paramat** [comment]
The proper fix is to fix `RemoteClient::GetNextBlocks` so it does not send a block that extends over0limit, this means that `blockpos_over_limit(p)` is failing.

**Comment by paramat** [comment]
In testing #4936 works well, although it won't fix the `createSector()` crash when a mob spawns over-limit.

**Comment by Rogier-5** [comment]
I think the following would fix the bug of mapblocks being loaded over limit:
```diff
diff --git a/src/mapblock.h b/src/mapblock.h
index 5adfcf3..daba54f 100644
--- a/src/mapblock.h
+++ b/src/mapblock.h
@@ -654,11 +654,11 @@ inline bool blockpos_over_limit(v3s16 p)
        const static u16 map_gen_limit = MYMIN(MAX_MAP_GENERATION_LIMIT,
                g_settings->getU16("map_generation_limit"));
        return (p.X < -map_gen_limit / MAP_BLOCKSIZE
-                       || p.X >  map_gen_limit / MAP_BLOCKSIZE
+                       || p.X >  (map_gen_limit + 1) / MAP_BLOCKSIZE - 1
                        || p.Y < -map_gen_limit / MAP_BLOCKSIZE
-                       || p.Y >  map_gen_limit / MAP_BLOCKSIZE
+                       || p.Y >  (map_gen_limit + 1) / MAP_BLOCKSIZE - 1
                        || p.Z < -map_gen_limit / MAP_BLOCKSIZE
-                       || p.Z >  map_gen_limit / MAP_BLOCKSIZE);
+                       || p.Z >  (map_gen_limit + 1 / MAP_BLOCKSIZE - 1);
 }
```
I expect that that should also avoid entities being created outside world limits. It should also prevent them being activated over limits, as those mapblocks would not be loaded to begin with.

Disclaimer: not tested yet.

As far as the creation of objects outside world limits goes: IMO lua code should either check that the object positon exists, of allow for the creation of the object to fail:
```lua
		boat = minetest.add_entity(pointed_thing.under, "boats:boat")
		if boat then
			boat:setyaw(placer:get_look_horizontal())
		end
```
The alternative solution would be to create the invalidly-positioned object anyway, and schedule it for deletion immediately thereafter. IMO that's just an ugly workaround to avoid having the fix broken mods.

**Comment by paramat** [comment]
Yeah, the problem with altering `blockpos_over_limit()` is that it is fed different types of value in different callbacks, so altering it here may break something else.

Allowing for deleted objects in Lua is a good workaround too, and is an alternative to #4936 however that produces error messages and prevents objects at world edge.

**Comment by paramat** [comment]
But then, #4936 may cause problems, it may be best to fix in Lua.

**Comment by paramat** [comment]
Yes we need to allow 'add entity' to fail without a crash anyway, as 'objectpos over limit' may happen for other reasons.

**Comment by paramat** [comment]
PR for falling.lua #4941

**Comment by paramat** [comment]
PR for boats https://github.com/minetest/minetest_game/pull/1468

**Comment by paramat** [comment]
If those are merged, remove the 0.4.15 milestone but keep this open for the proper fixes to map gen limit to be addressed.

**Comment by est31** [comment]
Its not a bug with the engine. The check for outside of mapgen limits was added in commit f61f817b9c170942a5b3ce3591125c2191645cd0 due to problems with entities outside of the F1000 limits.

It is a bug with builtin though, and if it occurs with worldedit, worldedit needs fixing too.

**Comment by sfan5** [comment]
related fixes were merged, mods might need fixing too

**Comment by paramat** [comment]
Please keep open as this contains a lot of useful discussion for after-release work, however the milestone can be removed.

**Comment by paramat** [comment]
#4941 and https://github.com/minetest/minetest_game/pull/1468 merged.

**Comment by paramat** [comment]
Testing again, generating a new world out to 500 in each direction of NESW, then setting map gen limit to 300 and seeing how far world loads:
N 303
S -288
E 303
W -288

So i agree with Rogier that this is a case of incorrect node / mapblock co-ord conversion in the positive direction.

**Comment by paramat** [comment]
#4965 may fix the remaining issues, @00c can you test?

**Comment by paramat** [comment]
#4965 merged.

**Comment by 00c** [comment]
Bug still exist, just compiled mt

> 2017-01-29 21:58:56: ACTION[Server]: Spawned Sheep at (4495,6,-4420)
2017-01-29 21:58:56: INFO[Server]: collisionMoveSimple: maximum step interval exceeded, lost movement details!
2017-01-29 21:58:57: ACTION[Server]: Spawned Sheep at (4462,6,-4394)
2017-01-29 21:58:58: ACTION[Server]: A sapling grows into a tree at (4488,5,-4385)
2017-01-29 21:58:58: ACTION[Server]: A sapling grows into a tree at (4495,9,-4392)
2017-01-29 21:58:58: ERROR[Server]: An unhandled exception occurred: createSector(): pos. over limit
2017-01-29 21:58:58: ERROR[Server]: In thread 7f5f87fff700:
2017-01-29 21:58:58: ERROR[Server]: /home/mt/src/server.cpp:72: virtual void* ServerThread::run(): A fatal error occured: createSector(): pos. over limit

**Comment by paramat** [comment]
This may be due to your mods though, boats mod had to be fixed.
To clarify, you originally generated world beyond 4500 in some places and then reduced the limit to 4500?

**Comment by 00c** [comment]
It was sheep or tree. Will try disable mobs mod.
I used a map tool to cut map outside 4500.

**Comment by paramat** [comment]
From above:
`ServerMap::createSector` is called by `ServerMap::emergeBlock` which is called by `ServerEnvironment::addActiveObjectRaw()`

`addActiveObjectRaw` is here https://github.com/minetest/minetest/blob/master/src/serverenvironment.cpp#L1639 and contains a check for object pos over limit, if within the limit it then calls `emergeBlock` https://github.com/minetest/minetest/blob/master/src/map.cpp#L2280 which calls `createSector` https://github.com/minetest/minetest/blob/master/src/map.cpp#L2033

So i'm thinking that an object may be spawned near the border:
>  Spawned Sheep at (4495,6,-4420)

This passes the test for being within limit, then the sector is created and there is a check here https://github.com/minetest/minetest/blob/master/src/map.cpp#L2068 for any part of the sector being over-limit.
It seems possible that the object is within the limit but the sector the object is in extends past the limit, causing the error.

**Comment by paramat** [comment]
The block / sector minpos is 4496, which means the sheep was in a block / sector that extends from 4496 to 4511.

**Comment by paramat** [comment]
I'll make a PR to edit objectpos_over_limit to keep objects more than 16 nodes within the map gen limit.

**Comment by paramat** [comment]
@00c where does the world end at the problematic location, 4495?

**Comment by 00c** [comment]
yes exact at 4495 it ends

**Comment by 00c** [comment]
There was a mob at border right now, mob stand on 4495, server did not crash.

**Comment by 00c** [comment]
Server crashes when i try to run full clearobjects

> 2017-02-01 17:44:27: ACTION[Server]: Evil clears all objects (full mode).
2017-02-01 17:45:01: ERROR[Server]: An unhandled exception occurred: createSector(): pos. over limit
2017-02-01 17:45:01: ERROR[Server]: In thread 7fbaba706700:
2017-02-01 17:45:01: ERROR[Server]: /home/mt/src/server.cpp:72: virtual void* ServerThread::run(): A fatal error occured: createSector(): pos. over limit
2017-02-01 17:45:01: ERROR[Server]: Debug stacks:
2017-02-01 17:45:01: ERROR[Server]: DEBUG STACK FOR THREAD 7fbab8af1700:
2017-02-01 17:45:01: ERROR[Server]: #0  virtual void* EmergeThread::run()
2017-02-01 17:45:01: ERROR[Server]: DEBUG STACK FOR THREAD 7fbab9704700:
2017-02-01 17:45:01: ERROR[Server]: #0  virtual void* EmergeThread::run()
2017-02-01 17:45:01: ERROR[Server]: DEBUG STACK FOR THREAD 7fbab9f05700:
2017-02-01 17:45:01: ERROR[Server]: #0  virtual void* CurlFetchThread::run()
2017-02-01 17:45:01: ERROR[Server]: DEBUG STACK FOR THREAD 7fbaba706700:
2017-02-01 17:45:01: ERROR[Server]: #0  virtual void* ServerThread::run()
2017-02-01 17:45:01: ERROR[Server]: DEBUG STACK FOR THREAD 7fbac0866740:
2017-02-01 17:45:01: ERROR[Server]: #0  int main(int, char**)
2017-02-01 17:45:01: ERROR[Server]: #1  Dedicated server branch
2017-02-01 17:45:01: ERROR[Server]: #2  void dedicated_server_loop(Server&, bool&)

**Comment by Fixer-007** [comment]
you need to build debug build and debug it with gdb

**Comment by 00c** [comment]
Growing tree trigger crash, mobs mod is off 

> 2017-02-06 01:25:13: ACTION[Server]: A sapling grows into a tree at (4490,6,-4384)
2017-02-06 01:25:13: ACTION[Server]: A sapling grows into a tree at (4493,8,-4377)
2017-02-06 01:25:13: ACTION[Server]: A sapling grows into a tree at (4494,9,-4375)
2017-02-06 01:25:13: ERROR[Server]: An unhandled exception occurred: createSector(): pos. over limit
2017-02-06 01:25:13: ERROR[Server]: In thread 7ff1e9639700:
2017-02-06 01:25:13: ERROR[Server]: /home/mt/src/server.cpp:72: virtual void* ServerThread::run(): A fatal error occured: createSector(): pos. over limit
2017-02-06 01:25:13: ERROR[Server]: Debug stacks:
2017-02-06 01:25:13: ERROR[Server]: DEBUG STACK FOR THREAD 7ff1e199c700:
2017-02-06 01:25:13: ERROR[Server]: #0  virtual void* EmergeThread::run()
2017-02-06 01:25:13: ERROR[Server]: DEBUG STACK FOR THREAD 7ff1e219d700:
2017-02-06 01:25:13: ERROR[Server]: #0  virtual void* EmergeThread::run()
2017-02-06 01:25:13: ERROR[Server]: DEBUG STACK FOR THREAD 7ff1e8e38700:
2017-02-06 01:25:13: ERROR[Server]: #0  virtual void* CurlFetchThread::run()
2017-02-06 01:25:13: ERROR[Server]: DEBUG STACK FOR THREAD 7ff1e9639700:
2017-02-06 01:25:13: ERROR[Server]: #0  virtual void* ServerThread::run()
2017-02-06 01:25:13: ERROR[Server]: DEBUG STACK FOR THREAD 7ff1efd9f740:
2017-02-06 01:25:13: ERROR[Server]: #0  int main(int, char**)
2017-02-06 01:25:13: ERROR[Server]: #1  Dedicated server branch
2017-02-06 01:25:13: ERROR[Server]: #2  void dedicated_server_loop(Server&, bool&)

**Comment by paramat** [comment]
Aha, so it looks like we need to allow a sector that extends over-limit to happen, because world will always extend to the limit and saplings will grow close to it.
I will have to change my fixing PR then, very useful thanks.

**Comment by paramat** [comment]
New PR #5184

**Comment by paramat** [comment]
I will revive #5157 as a new PR as that is also needed.

**Comment by paramat** [comment]
#5223 merged but please keep open as there are more issues to solve.

**Comment by paramat** [comment]
PR for remaning issues #5258

**Comment by paramat** [comment]
#5258 merged. Do re-open this issue if bugs persist.

**Comment by 00c** [comment]
Made some tests, all works fine, no crashes
Thanks for fix
