### ISSUE TITLE
Sneaking on 1/16th slab bug, and other sneak issues (new move code)

### ISSUE THREAD

**Issue by wilkgr76** [minetest/minetest#5438]
If you try to sneak on this wood, you fall off.
![screenshot_20170322_160716](https://cloud.githubusercontent.com/assets/12093476/24184447/b4da5032-0f19-11e7-8645-a278efe6004e.png)

**EDIT1:** Normal slabs also cause the character to fall off (from default game)

**Comment by sfan5** [comment]
Does this happen before 14aa990cdd682b00904c4a84968a6c0e3c31716d?

>Normal slabs also cause the character to fall off.

That seems weird, I tested that thoroughly.

**Comment by paramat** [comment]
Normal slabs work for me.

**Comment by bigfoot547** [comment]
That is a big fov :wink:!
I have tried normal slabs a while ago and it worked. Should I try again?

**Comment by DS-Minetest** [comment]
This only seems to happen with boxes less than 0.5 above floor.

_Perhaps a bit off-topic:_
But it's not the only new problem with sneak. I've also recognized somehow:
- sneaking into the node below
- teleportation to a certain pos of the node
- falling down if the node forward down is walkable but a nodebox
- you can't sneak walk from one node to another it the space is only one node high
- and more I think

**Comment by wilkgr76** [comment]
@bigfoot547 FOV is 120

The half slabs are the ones from default, not the sawn ones by the way.

**Comment by wilkgr76** [comment]
Interestingly, sometimes sneaking on snow works, sometimes it doesn't.
![screenshot_20170323_081046](https://cloud.githubusercontent.com/assets/12093476/24223080/4a609fc2-0fa0-11e7-9684-7cf0dfcfbc3b.png)

**Comment by wilkgr76** [comment]
Also, sneaking does not stop bouncing on bouncy blocks.

**Comment by Ezhh** [comment]
Did some tests of my own:

1. 1/16th nodes (I tested with bamboo planks from ethereal) no longer allow you to sneak from the edge. You simply drop off them when holding shift.
2. default:snow often gives the same result (though sometimes seems to work).
3. You can't walk across a default:snow or a 1/16 node while holding shift. To see this: drop a single node of default:snow on a flat surface, stand on the edge, hold shift and try to walk over it.  You walk into an invisible wall and can't cross with shift held.
4. Holding shift to sneak over an edge and then releasing it seems unreliable. Sometimes I fall, sometimes I don't.

**Comment by sfan5** [comment]
@Ezhh 
4. depends on whether you are pressing a movement key in the moment you release shift

**Comment by Ezhh** [comment]
@sfan5 
Maybe it's just me, but I would really appreciate an option to keep the old way of controlling sneak. Points 1 - 3 seem to be real issues regardless.

**Comment by paramat** [comment]
> Somehow it seems we swapped some (liked) bugs against some new (nasty) ones

It's actually the opposite, the old code had more serious bugs which were unfixable, the new code has minor bugs with a chance of being fixed.

**Comment by paramat** [comment]
![screenshot_20170324_032558](https://cloud.githubusercontent.com/assets/3686677/24279412/a8b9d614-1041-11e7-9d59-a6e087d6ab2f.png)

If this structure is surrounded by snow sneak works, if the snow is removed, it doesn't, this might explain why sneaking on snow only occsionally works.

With taller structures toppped with snow, sneak occasionally works.

Ezhh
> 4. Holding shift to sneak over an edge and then releasing it seems unreliable. Sometimes I fall, sometimes I don't.

Tested this and found you need to release the move key a fraction of a second or more before releasing the sneak key.
> 3. You can't walk across a default:snow or a 1/16 node while holding shift. To see this: drop a single node of default:snow on a flat surface, stand on the edge, hold shift and try to walk over it. You walk into an invisible wall and can't cross with shift held.

If you start not standing on the snow slab this does happen but it doesn't seem a problem.

Your points 1 and 2 i confirm above.

**Comment by paramat** [comment]
DS-Minetest
> sneaking into the node below

Can you explain this more?
> teleportation to a certain pos of the node

Confirmed if on the lower part of a stair node, sneak teleports you closer to the top part. Weird but not a big problem.
> falling down if the node forward down is walkable but a nodebox

Confirmed, if on a flat surface you have a full node next to a snow slab and sneak towards the snow sneak fails.
> you can't sneak walk from one node to another it the space is only one node high

Could this be done before? Confirmed but seems not problem, if the space is only 1 node high it's already impressive the player can sneak there.

**Comment by DS-Minetest** [comment]
- > > sneaking into the node below

> Can you explain this more?

Uhh, it's difficult. I just know, that sometimes I was beyond the node(nodebox) surface. Idk how to reproduce.

- > >  you can't sneak walk from one node to another it the space is only one node high

>Could this be done before? Confirmed but seems not a problem, if the space is only 1 node high it's already impressive the player can sneak there.

Before the sneak change this was possible and very useful. This could be related to @Ezhh's 3rd point:
> You can't walk across a default:snow or a 1/16 node while holding shift.

- Actually the biggest new problem in my opinion is that you can't jump if you are sneaking over the edge.

**Comment by paramat** [comment]
![screenshot_20170325_002845](https://cloud.githubusercontent.com/assets/3686677/24317712/169e99a2-10f2-11e7-9c81-ea72c8633c54.png)

Not sure if this was the case for old code, but noticed that if i sneak forwards in this direction i will fall off a rotated stair node.

**Comment by paramat** [comment]
With old code:

> 3.You can't walk across a default:snow or a 1/16 node while holding shift. To see this: drop a single node of default:snow on a flat surface, stand on the edge, hold shift and try to walk over it. You walk into an invisible wall and can't cross with shift held.

This also happens with old code, although the 'invisible barrier' encountered is smaller. Additionally you can sneak off the edge of the snow slab as far as you want (several node away) and remain floating just above ground.

Ezhh's point 2 does not happen with old code.

> if on a flat surface you have a full node next to a snow slab and sneak towards the snow sneak fails.

With old code this doesn't happen but something weirder happens, you can float way beyond the edge of the full node as if sneaking on the snow slabs below, but floating at full-node level, screenshot:

![screenshot_20170325_004147](https://cloud.githubusercontent.com/assets/3686677/24317837/35f75198-10f4-11e7-8661-7336c57cee5b.png)

> if i sneak forwards in this direction i will fall off a rotated stair node.

With old code i do not fall, but can sneak out to this position:

![screenshot_20170325_004545](https://cloud.githubusercontent.com/assets/3686677/24317864/864009ba-10f4-11e7-8c13-f10a309b2c2c.png)

As if it was a full node.

So, new code is not that much worse than old code.

**Comment by paramat** [comment]
Just wanted to mention a possible hacky workaround for being able to sneak out further. It depends on player collisonbox, which can be increased in size by altering mtg code.
There is also a PR for custom player collisionbox.

**Comment by paramat** [comment]
I tested master branch for sneaking-backwards-building-a-bridge-under-yourself because i had heard reports this is unreliable. This seems to work fine for me.

**Comment by paramat** [comment]
@Zeno- I tested master branch for sneaking-backwards-building-a-bridge-under-yourself because i had heard reports from you this is unreliable. This seems to work for me for full nodes, just remember to release the move key a fraction of a second before releasing the sneak key, then you will not drop.
Perhaps you could explain the problem and how to reproduce it?

**Comment by paramat** [comment]
![screenshot_20170329_013926](https://cloud.githubusercontent.com/assets/3686677/24433441/a07e858e-1420-11e7-98f6-0f989e0f982c.png)

With latest code, sneaking on a slab that is in the lower half of a node is unreliable, sometimes you can walk straight off. If the slab is in the upper half it is reliable.

**Comment by wilkgr76** [comment]
@paramat that is exactly what I was referring to by my edit.

**Comment by paramat** [comment]
![screenshot_20170329_020759](https://cloud.githubusercontent.com/assets/3686677/24434005/a9293da6-1424-11e7-86f3-0a646f9a6018.png)

Yes, after commit  https://github.com/minetest/minetest/commit/b85301ce69a3dc0763408dafc88cb4c1f56e53cf sneaking on half-slabs that are in the lower half of a node does not work, or occasionally works. Sneaking works reliably if the slabs are in the upper half.

**Comment by sfan5** [comment]
@paramat issue addressed: 5e806690fc5e0067247bbc1e541ba03b83fb761b

**Comment by paramat** [comment]
Thanks.

**Comment by paramat** [comment]
Confirmed lower-half slab bug now fixed.

**Comment by paramat** [comment]
#5476 adds the ability to pull-up onto a nearby ledge 2 nodes up, this is the other much wanted old behaviour, requested by many.

**Comment by paramat** [comment]
@wilkgr76 and @Ezhh 

> 1/16th nodes (I tested with bamboo planks from ethereal) no longer allow you to sneak from the edge. You simply drop off them when holding shift.

I tested latest master with a 1/16th nodebox on top of a full node, sneak seems to work, can either of you retest?

**Comment by tenplus1** [comment]
Before the changes it was possible to scale across ledges while holding sneak which made for some amazing parkour builds:

![sneakpic](http://i63.tinypic.com/xdftol.jpg)

**Comment by paramat** [comment]
https://github.com/minetest/minetest/issues/5438#issuecomment-288924770
> If this structure is surrounded by snow sneak works, if the snow is removed, it doesn't, this might explain why sneaking on snow only occsionally works.

> falling down if the node forward down is walkable but a nodebox

This seems fixed now.

**Comment by paramat** [comment]
![screenshot_20170401_094005](https://cloud.githubusercontent.com/assets/3686677/24577075/39be99e6-16bf-11e7-895f-14b1f8b857e7.png)

@tenplus1 sneaking across ledges works for me in latest.

**Comment by paramat** [comment]
Current remaining issues.
Sneaking along a ledge works for me but does not for tenplus1, which is odd.

"sneaking into the node below"

"falling down if the node forward down is walkable but a nodebox."
"Confirmed, if on a flat surface you have a full node next to a snow slab and sneak towards the snow sneak fails."

"Interestingly, sometimes sneaking on snow works, sometimes it doesn't."
"Sneaking from a node topped with snow when the node below is also topped with snow works. Sneaking from a node topped with snow when the node below is not topped with snow fails and lets you fall."
"If this structure is surrounded by snow sneak works, if the snow is removed, it doesn't, this might explain why sneaking on snow only occsionally works."

"You can't walk across a default:snow or a 1/16 node while holding shift. To see this: drop a single node of default:snow on a flat surface, stand on the edge, hold shift and try to walk over it. You walk into an invisible wall and can't cross with shift held."

"Actually the biggest new problem in my opinion is that you can't jump if you are sneaking over the edge."

"If i sneak forwards in this direction i will fall off a rotated stair node."

**Comment by paramat** [comment]
"Sneaking from a node topped with snow when the node below is also topped with snow works. Sneaking from a node topped with snow when the node below is not topped with snow fails and lets you fall."
"If this structure is surrounded by snow sneak works, if the snow is removed, it doesn't, this might explain why sneaking on snow only occsionally works."

This seems fixed now.

**Comment by paramat** [comment]
@DS-Minetest 
> you can't sneak walk from one node to another it the space is only one node high

Please test this with latest code as we are getting conflicting results.

**Comment by DS-Minetest** [comment]
With latest from daily ppa (perhaps not totally latest code >_<) it still doesn't work.

**Comment by paramat** [comment]
Bizarre. A build from after https://github.com/minetest/minetest/commit/5e806690fc5e0067247bbc1e541ba03b83fb761b is correct to try, i expect daily ppa will have that commit.

**Comment by paramat** [comment]
I've noticed that the new sneak ladder and my 2-node jump PR will not work if you are moving forward while sneak-jumping, are players used to pressing 'forward' while climbing a sneak ladder or pulliing-up onto a ledge?

**Comment by Ezhh** [comment]
@paramat I'm almost always pressing forward while using 2 node jump against ledges. (Sorry for being difficult!) Not so sure about for ladders.

**Comment by paramat** [comment]
No problem, i hope we can fix this.

**Comment by DS-Minetest** [comment]
> Bizarre. A build from after 5e80669 is correct to try, i expect daily ppa will have that commit.

Hm, it seems like I still have that bug with disabling hud with F2, so daily ppa is older than 9f4916a4528011b820c8bcbb3160bebda0cd2c2a, which is older than 5e80669.

**Comment by paramat** [comment]
Tenplus1 may have been using 'daily' ppa too. Can anyone who knows for sure they are using latest code check the sneaking across ledges bug?

**Comment by paramat** [comment]
@Ezhh 
> I'm almost always pressing forward while using 2 node jump against ledges

Testing old code, pressing forwards prevents a 2 node jump, so new code is no worse.

**Comment by Ezhh** [comment]
@paramat On current stable release, pressing forward while two node jumping works. I just tested to confirm.

**Comment by paramat** [comment]
Ok will test again.

**Comment by paramat** [comment]
Sorry you are correct, it was because i have jump = C and sneak = X (and so can never use sneak-jump), i guess the keyboard cannot process W+X+C somehow.

**Comment by paramat** [comment]
> I've noticed that the new sneak ladder and my 2-node jump PR will not work if you are moving forward against the nodes in front of you while sneak-jumping

Good news is that when testing with default key settings my 2 node jump PR works while pressing forwards.

**Comment by paramat** [comment]
> you can't sneak walk from one node to another it the space is only one node high
Before the changes it was possible to scale across ledges while holding sneak which made for some amazing parkour builds:

Confirmed that this is actually fixed.

**Comment by paramat** [comment]
Current remaining issues.

> "sneaking into the node below"
"Uhh, it's difficult. I just know, that sometimes I was beyond the node(nodebox) surface. Idk how to reproduce."

> "falling down if the node forward down is walkable but a nodebox."
"Confirmed, if on a flat surface you have a full node next to a snow slab and sneak towards the snow sneak fails."

> "You can't walk across a default:snow or a 1/16 node while holding shift. To see this: drop a single node of default:snow on a flat surface, stand on the edge, hold shift and try to walk over it. You walk into an invisible wall and can't cross with shift held."

> "Actually the biggest new problem in my opinion is that you can't jump if you are sneaking over the edge."

1 Is unconfirmed or difficulr to reproduce.
2 Is a minor issue, you land on the nodebox below.
3 Was also present in old code, although the invisible barrier was smaller. A fairly minor issue anyway.
4 We cannot jump from the edge of a node normally anyway due to an issue, is this much wanted for sneak behaviour?

**Comment by paramat** [comment]
4 above is fixed now i think.

**Comment by paramat** [comment]
Current remaining issues:

> "falling down if the node forward down is walkable but a nodebox."
"Confirmed, if on a flat surface you have a full node next to a snow slab and sneak towards the snow sneak fails."

> "You can't walk across a default:snow or a 1/16 node while holding shift. To see this: drop a single node of default:snow on a flat surface, stand on the edge, hold shift and try to walk over it. You walk into an invisible wall and can't cross with shift held."

> Sneak distance being smaller, 0.29 instead of 0.4.

1 Is a minor issue, you land on the nodebox below.
2 Was also present in old code, although the invisible barrier was smaller. A fairly minor issue anyway.
3 Seems an issue of getting used to the slightly smaller sneak distance, not a big issue.

All remaining issues are minor.

**Comment by SmallJoker** [comment]
Whatever is left over here.. did #9343 fix it?

**Comment by TheTermos** [comment]
> Whatever is left over here.. did #9343 fix it?

Because of all the controversy I reverted all changes to sneak in #9343 so if it does affect anything sneak related, it wasn't intended.

**Comment by appgurueu** [comment]
Duplicate of #9993?

**Comment by wilkgr76** [comment]
No...This bug report is 3 years older. 

I haven't actually played MT in a while - is this bug report even still valid, or can it be closed?

**Comment by appgurueu** [comment]
Can't reproduce with slabs or ethereal bamboo planks.
