### ISSUE TITLE
Jumping on a node higher than you will make you slowly fall until you land

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#664]
Jumping on a node will make you slowly fall until you land.

This bug was introduced by MirceaKitsune's physics changes. You can see it at the end of this video: https://www.youtube.com/watch?v=PESRAVcd8_0

**To reproduce this bug, put a walkable block in front of you then jump on it.**

It looks like the game thinks you're in water when that bug happens, since this bug depends on the water sinking speed.

**2014-08-15:** the bug is still here.

**Comment by gregorycu** [comment]
It's very possible that #2224 will fix this issue

**Comment by Yepoleb** [comment]
I did some research on this recently and here's what happens:

1. The `collisionMoveSimple` function gets called from `LocalPlayer::move` and sets touching_ground to true, because the player is less than 0.15 nodes above the ground.
2. `LocalPlayer::applyControl` gets called and sets the target speed to its default value 0. Then `accelerateVertical` sets the actual speed to the target speed. This doesn't happen while the player is in the air, because the condition at line 599 sets `incV` to 0, which skips the accelerate function. The condition is based on touching_ground.
3. `ClientEnvironment::step` applies gravity at line 2146 and moves the player, which gets us to step 1 again.

So `applyControl` sets the speed to 0, because it thinks the player is touching the ground, while he isn't. Gravity still gets applied and moves the player only a tiny bit. #2224 or the new version #3347 would indeed fix this.

**Comment by DS-Minetest** [comment]
this is already fixed, #3347 was merged: 60dc01d

**Comment by sfan5** [comment]
@DS-Minetest 60dc01dc258db842e229351b871d0989e3e7d62c was reverted because it caused other bugs.

**Comment by Fixer-007** [comment]
https://github.com/minetest/minetest/pull/3810

**Comment by Calinou** [comment]
Some updates:

- This still occurs with Minetest Git https://github.com/minetest/minetest/commit/60baf8120cdaabc619ab655065d95e8318e98412 by jumping onto any solid node that is 1 node higher than the player.
- Jumping onto a node while sneaking won't trigger this bug.
- This bug is not affected by horizontal player speed, it can be triggered even while using fast mode.

**Comment by paramat** [comment]
Happens rarely for me, depends on how you collide with the node you jump onto.

**Comment by paramat** [comment]
https://github.com/minetest/minetest/issues/664#issuecomment-158778984
"The collisionMoveSimple function gets called from LocalPlayer::move and sets touching_ground to true, because the player is less than 0.15 nodes above the ground."
This is confirmed by how this only happens when just above a solid node.

**Comment by rubenwardy** [comment]
Minetest movement has changed a lot since 2013

**Comment by v-rob** [comment]
Still happens in dev, I can reproduce.  It's a pretty small bug, however, and I rarely encounter it or pay any attention to it.

**Comment by sfan5** [comment]
Really? I haven't seen this bug at all since approximately the collision rework.

**Comment by Calinou** [comment]
I can't reproduce this anymore as of https://github.com/minetest/minetest/commit/f85e9ab9254e2ae4ac13170f9edea00fb8d931a2. 
Thanks for fixing this :slightly_smiling_face:
