### ISSUE TITLE
Non-opaque nodes are 1 light level darker than they should be

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#723]
This causes allfaces, allfaces_optional, fencelike, glasslike, nodebox, raillike, signlike... nodes to have darker textures than they should have, unless they're using sunlight_propagates = true.

A fix would be to enable sunlight_propagates = true by default for these drawtypes. These nodes (especially nodeboxes) could also be drawn one light level brighter than they should be when they don't have sunlight_propagates = true.

**Comment by RobertZenz** [comment]
I'm seeing similar lighting issues with nodes that use meshes.

![bsmsifc](https://cloud.githubusercontent.com/assets/611377/9597732/17ca60ce-5085-11e5-9875-b59ec83201a2.png)

You're looking at mesh nodes that make up ramps for the stone. Notice that they are oddly lit, this is directly after my callback registered at `on_generated` is executed (using the VoxelManip and `calc_lighting` is called. If I load the block again in a VoxelManip object, just read and set the data and run `calc_lighting` again it becomes *better*, but there still is a lighting difference.

**Comment by paramat** [comment]
The original issue is fixed i think due to the conversion of nodeboxes to meshnodes.
However meshnodes will still look different because they are non-cubic and smooth lighting doesn't function for them.

**Comment by kilbith** [comment]
Smooth lighting don't work on nodeboxes as well. Look for example on snow layers under a tree.

**Comment by RobertZenz** [comment]
@paramat You're right, it is the smooth lighting that makes them look odd. If I turn it off they look better and less out of place.

My other lighting issues could be explained with being close to block borders, though, I'll look into it some time to see if it really is that.

**Comment by RobertZenz** [comment]
Nope, I'm still seeing issues right after a block has been generated.

This is righter after the block has been deleted and regenerated:
![screenshot_20150901_222456](https://cloud.githubusercontent.com/assets/611377/9615442/527a3e24-50f8-11e5-9b99-4fdca96d09aa.png)

This is after running `calc_lighting` again:
![screenshot_20150901_222504](https://cloud.githubusercontent.com/assets/611377/9615443/527a4fa4-50f8-11e5-921d-e8a6e7f0094b.png)

**Comment by paramat** [comment]
I assume you're using the 'mapgen object voxelmanip' for terrain generation. Don't use 'update map' that is another slower lighting update used ny 'non mapgen object voxelmanip' only. This might fix your bug and speed up mapgen. 'Update map' is known to be slow and produce lighting bugs.

I explored your Australopithecus game, stunning, but the slowest and heaviest lua mapgen i have tried, even heavier than riverdev =)

**Comment by RobertZenz** [comment]
Mh, without `update_map()` the lighting stays at the first version (first screenshot, the brighter one). That is inside a cave without any light sources nearby. If I place a light source and remove it again, it switches to the darker version (second screenshot). If I regenerate the block, it is bright again.

The code that is used now equals yours...so, there is still something odd I'd say.

**Comment by ExeterDad** [comment]
@RobertZenz 
About your issue of the lighting being different from meshnode to meshnode. I ran into this while making slopes for Don's myroofs mod. Turned out the normals checkbox needs selected when exporting the model from Blender. It fixed our odd shading issues.

**Comment by RobertZenz** [comment]
@ExeterDad That is a different one, I fixed that one months ago thanks to your hint. :)

**Comment by RobertZenz** [comment]
@paramat You can find the exact code that I use in the [MapManipulator.set_data()](https://github.com/RobertZenz/minetest-australopithecus-utils/blob/master/utils/mapmanipulator.lua) function.

**Comment by paramat** [comment]
> without update_map() the lighting stays at the first version (first screenshot, the brighter one)
The 'calc lighting' used in mapgen is faster and simpler than 'upate map', so is probably causing subtle lighting bugs with meshnodes because of it's simplicity.

**Comment by RobertZenz** [comment]
They seem to be present everywhere, I'm not in front of my main PC so testing is a little bit tedious, but I can remember seeing lighting problems under overhangs and I also looked into some caves right now and they all had that problem.

**Comment by RobertZenz** [comment]
I just did some further testing and mesh nodes seem to have incorrect lighting throughout the whole map (mostly visible in caves, as they are very bright, but also under overhangs and similar).

**Comment by HybridDog** [comment]
>I just did some further testing and mesh nodes seem do have incorrect lighting throughout the whole map (mostly visible in caves, as they are very bright, but also under overhangs and similar) directly after mapgen.

paramtype "light" nodes are treated different, you can test it by playing around with mapblock_mesh.cpp
afaik, nodes without paramtype "light" take the light from the nodes next to them, usually "air"
